# Zadanie 5: programowanie genetyczne i regresja symboliczna

Adam Tokarz, Serhii Zeliuk

EAIIIB ISI Metody i algorytmy optymalizacji grupa laboratoryjna 2 poniedziałek 18:30

Termin realizacji: 12 maja 2025

Zadanie do oddania przez MS Teams. Do oddania: kod oraz krótkie sprawozdanie w PDF (można na przykład przy użyciu `quarto render notebook.ipynb --to pdf`).

## Na 3.0

Do realizacji:

1. Zmodyfikuj przykład `pysr_demo.ipynb` tak, aby uczył się funkcji $f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$ której dziedziną jest $\mathbb{R}^6$. Uczenie ma się odbywać w oparciu o 200 wylosowanych z dziedziny próbek (między -5 a 5).
2. Zanotuj wzory trzech rozwiązań o najwyższej wartości `score` oraz rozwiązanie `best` dla następujących zestawów ustawień:
   1. `binary_operators=["+", "*"], unary_operators=["cos", "exp", "sin"], maxsize=20`,
   2. `binary_operators=["+", "*", "-", "^"], unary_operators=["cos", "exp", "sin", "log"], maxsize=30`, (dodaj ograniczenie dla argumentów operatora "^").
   3. `binary_operators=["+", "*", "-", "^"], unary_operators=["exp", "sin"], maxsize=15`.
3. Powtórz eksperymenty z zadania na 3.0 po dodaniu szumu do próbek z funkcji $f$ (rozkład normalny o średniej 0 i odchyleniu standardowym 0.5)

## Na 4.0

Do realizacji:

1. Punkty z zadania na 3.0.
2. Dodaj do porównania dopasowanie oparte o próbki losowane w szerszym zakresie (między -15 a 15) oraz wyższy poziom szumu (odchylenie standardowe równe 2 oraz 5).

## Na 5.0

Do realizacji:

1. Punkty z zadania na 4.0.
2. Zamień funkcję $f$ na $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$ gdzie $p(i)$ oznacza $i$-tą liczbę pierwszą. Uwzględnij `p` jako dodatkowy operator unarny analogicznie do przykładu "Julia packages and types" z notatnika `pysr_demo.ipynb`. Powtórz eksperymenty opisane w zadaniach na 3.0 i 4.0.

In [112]:
import pysr
import sympy
import numpy as np
from matplotlib import pyplot as plt
from pysr import PySRRegressor
from sklearn.model_selection import train_test_split

# 5.1 Function f [3.0]

$$f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$$

- X (random values  $\mathbb{R}^6$ [-5, 5])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev = 0.5)

In [113]:
from numpy import sin, cos, exp, log, sqrt
# Dataset

np.random.seed(0)
X = np.random.uniform(-5, 5, size=(200, 6))
# y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 2
y = 2.2*sin(X[:, 0] + 2*X[:, 1]) - X[:, 5] ** 2 - 3
# Add the y samples with random noise
noise = np.random.normal(loc=0.0, scale=0.5, size=y.shape)
y_noisy = y + noise

In [114]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

# 5.2 Experiments [3.0]

## 5.2.1 Model 1

In [115]:
model_1 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.159
3           5.546e+01  1.240e-03  y = x₂ + -11.311
4           5.152e+01  7.370e-02  y = cos(x₅) + -10.987
5           6.759e+00  2.031e+00  y = x₅ * (x₅ * -1.1931)
7           2.205e+00  5.600e-01  y = ((x₅ * x₅) * -0.98155) + -3.1631
9           2.197e+00  1.884e-03  y = (x₅ * ((x₅ + 0.033226) * -0.9792)) + -3.1777
11          2.132e+00  1.506e-02  y = (x₅ * ((x₅ + (x₄ * -0.03464)) * -0.98024)) + -3.1802
12          2.132e+00  7.033e-06  y = (x₅ * ((x₅ + sin(x₄ * -0.034774)) * -0.98022)) + -3.18...
                                      04
13          2.087e+00  2.140e-02  y = (x₅ * (x₅ * -0.98951)) + (cos(cos(x₁ + 0.76523)) * -4....
                                      0602)
14          1.965e+00  6.013e-02  y = (((x₅ * x₅) + 4.0164) * -0.98171) + cos(cos(x₁ + cos(x...
                                      ₀)))
16          6.557e-01  5.487e-01  y = cos(x₁ + (x₀ + (x₁ + -1.5521))) + (((x₅ * x₅) + 3.1199...
                                      ) * -0.99003)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.158757
	1         0.001240                                    x2 + -11.310887
	2         0.073704                               cos(x5) + -10.987488
	3         2.031154                             x5 * (x5 * -1.1931313)
	4         0.560019               ((x5 * x5) * -0.9815453) + -3.163114
	5         0.001884  (x5 * ((x5 + 0.03322611) * -0.97919816)) + -3....
	6         0.015061  (x5 * ((x5 + (x4 * -0.03463991)) * -0.9802352)...
	7         0.000007  (x5 * ((x5 + sin(x4 * -0.034773707)) * -0.9802...
	8         0.021403  (x5 * (x5 * -0.9895081)) + (cos(cos(x1 + 0.765...
	9         0.060134  (((x5 * x5) + 4.016402) * -0.98170984) + cos(c...
	10  >>>>  0.548707  cos(x1 + (x0 + (x1 + -1.5520582))) + (((x5 * x...

	         loss  complexity
	0   55.599790           1
	1   55.462025           3
	2   51.521240           4
	3    6.758768           5
	4    2.205166           7
	5    2.196871           9
	6    2.131682          11
	7    2.131667          12
	8    2.086528          13
	9    1.964755          14
	10   0.655703          16
]

  - outputs\20250511_142020_mmZHHv\hall_of_fame.csv

### Model 1 best + top3 according to score

In [116]:
best_equation_1 = model_1.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: (x5*x5 + 3.1199038)*(-0.9900283) + cos(x0 + x1 + x1 - 1.5520582)
Index 3, score=2.031154
Equation: x5 * (x5 * -1.1931313)

Index 4, score=0.560019
Equation: ((x5 * x5) * -0.9815453) + -3.163114

Index 10, score=0.548707
Equation: cos(x1 + (x0 + (x1 + -1.5520582))) + (((x5 * x5) + 3.1199038) * -0.9900283)

## 5.2.2 Model 2

Added constraint to operator "^" - safe_pow

In [117]:
%%julia
function safe_pow(x::T, y::T) where T
    if(x < 0 && floor(y) != y)
        return T(NaN)
    else
        return T(x^y)
    end
end

safe_pow (generic function with 2 methods)

In [118]:
def safe_pow(x, y):
    if x < 0 and np.floor(y) != y:
        return np.nan
    return np.power(x, y)

model_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.159
3           5.537e+01  2.051e-03  y = -11.021 - x₅
4           5.152e+01  7.208e-02  y = cos(x₅) + -10.987
5           2.224e+00  3.143e+00  y = -3.0129 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = (x₅ * (x₅ * -0.98155)) - 3.1631
9           2.197e+00  1.884e-03  y = (-3.2452 - (x₅ * (x₅ - -0.033213))) * 0.9792
10          2.195e+00  7.221e-04  y = (-3.093 - (x₅ * x₅)) + (exp(x₄) * 0.0051806)
11          2.111e+00  3.935e-02  y = (-3.795 - (x₅ * x₅)) + cos(cos(x₁ + -7.059))
12          1.982e+00  6.303e-02  y = cos(cos(x₁ + cos(x₀))) + (-3.8054 - (x₅ * x₅))
14          1.965e+00  4.219e-03  y = cos(cos(x₁ + cos(x₀ + 0.29666))) + (-3.8056 - (x₅ * x₅...
                                      ))
16          1.901e+00  1.668e-02  y = cos(cos(x₁ + cos(x₀ + 0.18016)) + -0.40873) - ((x₅ * x...
                                      ₅) - -3.6706)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.158837
	1         0.002051                                    -11.020784 - x5
	2         0.072084                               cos(x5) + -10.987488
	3   >>>>  3.142667                             -3.0129306 - (x5 * x5)
	4         0.004262               (x5 * (x5 * -0.98154575)) - 3.163109
	5         0.001884  (-3.245216 - (x5 * (x5 - -0.033213433))) * 0.9...
	6         0.000722  (-3.0930007 - (x5 * x5)) + (exp(x4) * 0.005180...
	7         0.039353  (-3.7949667 - (x5 * x5)) + cos(cos(x1 + -7.058...
	8         0.063031  cos(cos(x1 + cos(x0))) + (-3.8053768 - (x5 * x5))
	9         0.004219  cos(cos(x1 + cos(x0 + 0.29666355))) + (-3.8056...
	10        0.016678  cos(cos(x1 + cos(x0 + 0.1801611)) + -0.4087252...

	         loss  complexity
	0   55.599790           1
	1   55.372204           3
	2   51.521240           4
	3    2.224043           5
	4    2.205166           7
	5    2.196871           9
	6    2.195285          10
	7    2.110572          11
	8    1.981646          12
	9    1.964994          14
	10   1.900530          16
]

  - outputs\20250511_142022_ypBn8q\hall_of_fame.csv

In [119]:
best_equation_2 = model_2.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 3.0129306
Index 3, score=3.142667
Equation: -3.0129306 - (x5 * x5)

Index 2, score=0.072084
Equation: cos(x5) + -10.987488

Index 8, score=0.063031
Equation: cos(cos(x1 + cos(x0))) + (-3.8053768 - (x5 * x5))

## 5.2.3 Model 3

In [120]:
model_3 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.158
3           5.537e+01  2.051e-03  y = -11.021 - x₅
4           5.462e+01  1.364e-02  y = -11.157 - sin(x₀)
5           2.224e+00  3.201e+00  y = -3.0143 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = (x₅ * (x₅ * -0.98155)) + -3.1631
9           2.197e+00  1.884e-03  y = (x₅ * ((x₅ * -0.9792) + -0.032516)) + -3.1777
11          2.173e+00  5.516e-03  y = ((x₅ * (x₅ * -0.98035)) + -3.1557) - (x₀ * -0.059193)
12          2.166e+00  3.349e-03  y = (((x₅ * x₅) * -0.97994) + -2.1313) - exp(x₀ * -0.07108...
                                      3)
13          2.147e+00  8.441e-03  y = ((x₅ * (x₅ * -0.97882)) + -3.175) - ((x₃ - x₀) * 0.054...
                                      265)
14          2.131e+00  7.656e-03  y = ((x₅ * (x₅ * -0.97943)) + -3.8798) - sin(-1.8269 - (x₀...
                                       * -0.24514))
15          2.097e+00  1.598e-02  y = ((x₅ * x₅) * -0.97894) + (-3.8163 - sin(-1.0071 - sin(...
                                      x₀ * -1.0349)))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142026_LotbFM\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.158208
	1         0.002051                                    -11.020789 - x5
	2         0.013642                                 -11.1574 - sin(x0)
	3   >>>>  3.201108                             -3.0142558 - (x5 * x5)
	4         0.004263             (x5 * (x5 * -0.98154527)) + -3.1631148
	5         0.001884  (x5 * ((x5 * -0.9792017) + -0.032515757)) + -3...
	6         0.005516  ((x5 * (x5 * -0.9803524)) + -3.1557028) - (x0 ...
	7         0.003349  (((x5 * x5) * -0.9799441) + -2.1313317) - exp(...
	8         0.008441  ((x5 * (x5 * -0.97881573)) + -3.1750479) - ((x...
	9         0.007656  ((x5 * (x5 * -0.97943085)) + -3.8797712) - sin...
	10        0.015979  ((x5 * x5) * -0.97893745) + (-3.816306 - sin(-...

	         loss  complexity
	0   55.599790           1
	1   55.372204           3
	2   54.621952           4
	3    2.224045           5
	4    2.205166           7
	5    2.196871           9
	6    2.172767          11
	7    2.165502          12
	8    2.147300          13
	9    2.130922          14
	10   2.097144          15
]

In [121]:
best_equation_3 = model_3.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 3.0142558
Index 3, score=3.201108
Equation: -3.0142558 - (x5 * x5)

Index 10, score=0.015979
Equation: ((x5 * x5) * -0.97893745) + (-3.816306 - sin(-1.0071386 - sin(x0 * -1.0348505)))

Index 2, score=0.013642
Equation: -11.1574 - sin(x0)

## 5.2.4 Model 1 with noise

In [122]:
model_1_noisy.fit(X, y_noisy)
best_equation_1_noisy = model_1_noisy.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1_noisy.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.092
3           5.560e+01  5.027e-04  y = x₂ + -11.245
4           5.159e+01  7.493e-02  y = cos(x₅) + -10.922
5           6.855e+00  2.018e+00  y = (x₅ * -1.188) * x₅
7           2.449e+00  5.148e-01  y = ((x₅ * x₅) * -0.97983) + -3.1116
9           2.434e+00  2.937e-03  y = (x₅ * ((x₅ * -0.97674) + -0.042771)) + -3.1309
11          2.363e+00  1.485e-02  y = (x₅ * ((x₅ * -0.97839) + (x₄ * 0.036654))) + -3.1303
12          2.346e+00  7.329e-03  y = (sin(x₀) * -0.44094) + ((x₅ * (x₅ * -0.97556)) + -3.14...
                                      59)
13          2.345e+00  1.626e-04  y = (x₅ * (((x₅ * -0.97494) + -0.04748) + (x₄ * 0.037387))...
                                      ) + -3.152
14          2.326e+00  8.396e-03  y = (((x₅ * -0.97727) + ((x₄ + cos(x₀)) * 0.043133)) * x₅)...
                                       + -3.139
16          2.313e+00  2.746e-03  y = (((x₅ * -0.97442) + ((x₄ + cos(x₀)) * 0.042799)) * (x₅...
                                       + 0.041377)) + -3.1561
17          2.300e+00  5.426e-03  y = (x₅ * ((x₅ * -0.97638) + (((x₄ + cos(x₀)) + cos(x₀)) *...
                                       0.044021))) + -3.1444
18          2.297e+00  1.319e-03  y = (x₅ * (((x₄ + cos(x₀)) * 0.042261) + (x₅ * -0.97623)))...
                                       + ((x₀ * 0.055357) + -3.1311)
19          2.293e+00  1.896e-03  y = (((x₅ * -0.97425) + (((x₄ + cos(x₀)) + cos(x₀)) * 0.04...
                                      3132)) * (x₅ + 0.031612)) + -3.1568
20          2.279e+00  6.086e-03  y = (x₅ * ((((cos(x₀) + x₄) * -0.045106) + x₅) * -0.97204)...
                                      ) + (((x₅ + x₃) * -0.05093) + -3.1796)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142029_0pIYpG\hall_of_fame.csv
Best by score: x5*x5*(-0.9798251) - 3.1116428
Index 3, score=2.018258
Equation: (x5 * -1.1879656) * x5

Index 4, score=0.514755
Equation: ((x5 * x5) * -0.9798251) + -3.1116428

Index 2, score=0.074934
Equation: cos(x5) + -10.9218025

## 5.2.5 Model 2 with noise

In [123]:
model_2_noisy.fit(X, y_noisy)
best_equation_2_noisy = model_2_noisy.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2_noisy.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.092
3           5.528e+01  3.374e-03  y = -10.955 - x₅
4           5.159e+01  6.919e-02  y = cos(x₅) + -10.922
5           2.471e+00  3.039e+00  y = -2.9473 - (x₅ * x₅)
7           2.449e+00  4.586e-03  y = (x₅ * (x₅ * -0.97982)) + -3.1117
9           2.434e+00  2.937e-03  y = (((x₅ + 0.043789) * -0.97674) * x₅) - 3.1309
11          2.434e+00  -0.000e+00  y = (((x₅ + 0.043716) * (x₅ * -0.97676)) - 107.02) + 103....
                                       89
12          2.408e+00  1.061e-02  y = ((x₅ * (x₅ * -0.97957)) + -3.2084) + exp(x₄ - 5.0981)
14          2.395e+00  2.847e-03  y = exp(x₄ - 5.1061) + (((x₅ * (x₅ - -0.042768)) * -0.9765...
                                      8) + -3.2261)
15          2.197e+00  8.636e-02  y = (safe_pow(x₅ * x₅, 1.051) * -0.8266) + (sin(exp(x₅ + 3...
                                      .0566)) + -3.6429)
16          2.181e+00  7.252e-03  y = (safe_pow(x₅ * x₅, 1.0527) * -0.82232) + (sin(sin(exp(...
                                      x₅ + 3.0564))) + -3.5542)
17          2.163e+00  8.410e-03  y = sin(exp(x₅ + 3.0563)) + (((safe_pow(x₅ * x₅, 0.99074) ...
                                      - 0.28408) * -0.99814) + -3.5451)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142031_LH45I0\hall_of_fame.csv
Best by score: -x5*x5 - 2.9473078
Index 3, score=3.038596
Equation: -2.9473078 - (x5 * x5)

Index 9, score=0.086357
Equation: (safe_pow(x5 * x5, 1.0510213) * -0.82659906) + (sin(exp(x5 + 3.0565894)) + -3.642883)

Index 2, score=0.069191
Equation: cos(x5) + -10.922012

## 5.2.6 Model 3 with noise

In [124]:
model_3_noisy.fit(X, y_noisy)
best_equation_3_noisy = model_3_noisy.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3_noisy.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.093
3           5.528e+01  3.374e-03  y = -10.955 - x₅
4           5.467e+01  1.109e-02  y = -11.092 - sin(x₀)
5           2.471e+00  3.097e+00  y = -2.9475 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = (x₅ * (x₅ * -0.97983)) + -3.1116
9           2.434e+00  2.937e-03  y = (x₅ * ((x₅ * -0.97674) + -0.042794)) - 3.1308
11          2.363e+00  1.485e-02  y = (x₅ * ((x₄ * 0.036647) + (x₅ * -0.97839))) + -3.1303
13          2.345e+00  3.746e-03  y = (x₅ * (((x₄ + -1.271) * 0.037382) + (x₅ * -0.97494))) ...
                                      + -3.152
15          2.336e+00  2.011e-03  y = ((x₅ + 0.62089) * ((((x₄ * -0.038841) + -0.57139) + x₅...
                                      ) * -0.97525)) + -3.4949
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: -x5*x5 - 2.9474645
Index 3, score=3.096697
Equation: -2.9474645 - (x5 * x5)

Index 6, score=0.014852
Equation: (x5 * ((x4 * 0.036646537) + (x5 * -0.97839344))) + -3.1303284

Index 2, score=0.011090
Equation: -11.0919695 - sin(x0)

  - outputs\20250511_142034_ftnakZ\hall_of_fame.csv

# 5.3 Output into a DF [3.0]

In [125]:
import pandas as pd

data = []

for model_name in ['model_1', 'model_2', 'model_3','model_1_noisy', 'model_2_noisy', 'model_3_noisy']:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1,best,(x5*x5 + 3.1199038)*(-0.9900283) + cos(x0 + x1...,2.031154
1,model_1,3,x5 * (x5 * -1.1931313),2.031154
2,model_1,4,((x5 * x5) * -0.9815453) + -3.163114,0.560019
3,model_1,10,cos(x1 + (x0 + (x1 + -1.5520582))) + (((x5 * x...,0.548707
4,model_2,best,-x5*x5 - 3.0129306,3.142667
5,model_2,3,-3.0129306 - (x5 * x5),3.142667
6,model_2,2,cos(x5) + -10.987488,0.072084
7,model_2,8,cos(cos(x1 + cos(x0))) + (-3.8053768 - (x5 * x5)),0.063031
8,model_3,best,-x5*x5 - 3.0142558,3.201108
9,model_3,3,-3.0142558 - (x5 * x5),3.201108
10,model_3,10,((x5 * x5) * -0.97893745) + (-3.816306 - sin(-...,0.015979
11,model_3,2,-11.1574 - sin(x0),0.013642
12,model_1_noisy,best,x5*x5*(-0.9798251) - 3.1116428,2.018258
13,model_1_noisy,3,(x5 * -1.1879656) * x5,2.018258
14,model_1_noisy,4,((x5 * x5) * -0.9798251) + -3.1116428,0.514755
15,model_1_noisy,2,cos(x5) + -10.9218025,0.074934
16,model_2_noisy,best,-x5*x5 - 2.9473078,3.038596
17,model_2_noisy,3,-2.9473078 - (x5 * x5),3.038596
18,model_2_noisy,9,"(safe_pow(x5 * x5, 1.0510213) * -0.82659906) +...",0.086357
19,model_2_noisy,2,cos(x5) + -10.922012,0.069191
20,model_3_noisy,best,-x5*x5 - 2.9474645,3.096697
21,model_3_noisy,3,-2.9474645 - (x5 * x5),3.096697
22,model_3_noisy,6,(x5 * ((x4 * 0.036646537) + (x5 * -0.97839344)...,0.014852
23,model_3_noisy,2,-11.0919695 - sin(x0),0.011090

In [126]:
df.to_csv('results3.csv')

# 5.4 Function f [4.0]

$$f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$$

- X (random values  $\mathbb{R}^6$ [-15, 15])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev1 = 2, std_dev2 = 5)

In [127]:
from numpy import sin, cos, exp, log, sqrt
# Dataset

np.random.seed(0)
X = np.random.uniform(-15, 15, size=(200, 6))
# y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 2
y = 2.2*sin(X[:, 0] + 2*X[:, 1]) - X[:, 5] ** 2 - 3
# Add the y samples with random noise
noise1 = np.random.normal(loc=0.0, scale=2, size=y.shape)
y_noisy1 = y + noise1
noise2 = np.random.normal(loc=0.0, scale=5, size=y.shape)
y_noisy2 = y + noise2

In [128]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

# 5.5 Experiments [4.0]

## 5.5.1 Model 1

In [129]:
model_1_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.289
3           4.338e+03  1.665e-02  y = x₂ + -76.738
5           6.228e+00  3.273e+00  y = x₅ * (x₅ * -1.0218)
7           2.054e+00  5.546e-01  y = (x₅ * (x₅ * -0.99929)) + -3.0285
9           2.022e+00  7.920e-03  y = ((x₅ + -0.02139) * (x₅ * -0.99981)) + -2.9997
11          2.022e+00  3.576e-07  y = ((x₅ + -0.66844) * ((x₅ * -0.9998) + -0.64693)) + -3.4...
                                      321
13          1.984e+00  9.388e-03  y = (cos(exp(x₅)) + ((x₅ * (x₅ * 2.931)) + 8.2596)) * -0.3...
                                      4112
14          1.911e+00  3.777e-02  y = (sin(x₀ * -1.4146) + (((x₅ * x₅) * 1.6774) + 5.1155)) ...
                                      * -0.59566
17          1.909e+00  2.574e-04  y = ((x₅ * (x₅ * 2.1343)) + (sin((x₀ * -1.4117) + cos(x₅))...
                                       + 6.3564)) * -0.46818
18          1.895e+00  7.483e-03  y = ((x₅ * (x₅ * 2.0776)) + (sin((x₀ * -1.3998) + sin(cos(...
                                      x₅))) + 6.2964)) * -0.48092
20          1.818e+00  2.073e-02  y = (((x₅ * x₅) * 2.0378) + (sin(x₃ + x₂) + (sin(exp(x₅) +...
                                       1.098) + 5.6553))) * -0.49067
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142036_d1pRcF\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick         score                                           equation  \
	0         0.000000e+00                                          -76.28889
	1         1.665117e-02                                      x2 + -76.7383
	2         3.273026e+00                             x5 * (x5 * -1.0218015)
	3   >>>>  5.546360e-01              (x5 * (x5 * -0.9992923)) + -3.0284927
	4         7.920023e-03  ((x5 + -0.021390438) * (x5 * -0.9998059)) + -2...
	5         4.204162e-07  ((x5 + -0.6684413) * ((x5 * -0.9998026) + -0.6...
	6         9.388013e-03  (cos(exp(x5)) + ((x5 * (x5 * 2.9310462)) + 8.2...
	7         3.777084e-02  (sin(x0 * -1.4146291) + (((x5 * x5) * 1.677411...
	8         2.574637e-04  ((x5 * (x5 * 2.1342719)) + (sin((x0 * -1.41166...
	9         7.483190e-03  ((x5 * (x5 * 2.0776234)) + (sin((x0 * -1.39975...
	10        2.073458e-02  (((x5 * x5) * 2.0378149) + (sin(x3 + x2) + (si...

	           loss  complexity
	0   4484.837400           1
	1   4337.941400           3
	2      6.228301           5
	3      2.054087           7
	4      2.021807           9
	5      2.021805          11
	6      1.984198          13
	7      1.910651          14
	8      1.909175          17
	9      1.894942          18
	10     1.817967          20
]

### Model 1 best + top3 according to score

In [130]:
best_equation_1 = model_1_wide_range.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x5*x5*(-0.9992923) - 3.0284927
Index 2, score=3.273026
Equation: x5 * (x5 * -1.0218015)

Index 3, score=0.554636
Equation: (x5 * (x5 * -0.9992923)) + -3.0284927

Index 7, score=0.037771
Equation: (sin(x0 * -1.4146291) + (((x5 * x5) * 1.6774113) + 5.1155124)) * -0.5956648

## 5.5.2 Model 2

In [131]:

model_2_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.289
3           4.338e+03  1.665e-02  y = x₂ + -76.741
5           2.056e+00  3.827e+00  y = -2.9765 - (x₅ * x₅)
7           2.022e+00  8.427e-03  y = ((0.021661 - x₅) * x₅) + -2.9856
9           2.022e+00  3.997e-05  y = (((0.021392 - x₅) * x₅) + -3.0003) * 0.9998
11          2.022e+00  -0.000e+00  y = ((((0.021396 - x₅) * x₅) + -2.4217) * 0.99981) + -0.5...
                                       7834
12          2.008e+00  6.884e-03  y = (((0.022038 - x₅) * x₅) + (exp(x₁) * -2.5869e-07)) + -...
                                      2.9541
13          1.606e+00  2.235e-01  y = (sin((sin(x₁) * -2.7745) + x₀) - 2.9173) - (x₅ * x₅)
14          6.090e-01  9.696e-01  y = (sin((x₁ * 1.9949) + (x₀ + -0.025346)) - 2.9843) - (x₅...
                                       * x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142038_uk6pk6\hall_of_fame.csv

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	   pick         score                                           equation  \
	0        0.000000e+00                                          -76.28887
	1        1.665121e-02                                    x2 + -76.740746
	2        3.827115e+00                             -2.9764934 - (x5 * x5)
	3        8.427082e-03             ((0.021661282 - x5) * x5) + -2.9856086
	4        4.001211e-05  (((0.021392243 - x5) * x5) + -3.0002518) * 0.9...
	5        4.946070e-08  ((((0.021396048 - x5) * x5) + -2.4217439) * 0....
	6        6.884586e-03  (((0.02203849 - x5) * x5) + (exp(x1) * -2.5869...
	7        2.234522e-01  (sin((sin(x1) * -2.7745197) + x0) - 2.9173124)...
	8  >>>>  9.695744e-01  (sin((x1 * 1.9949355) + (x0 + -0.02534592)) - ...

	          loss  complexity
	0  4484.837400           1
	1  4337.941000           3
	2     2.056336           5
	3     2.021969           7
	4     2.021807           9
	5     2.021807          11
	6     2.007935          12
	7     1.605853          13
	8     0.609011          14
]

In [132]:
best_equation_2 = model_2_wide_range.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 + sin(x0 + x1*1.9949355 - 0.02534592) - 1*2.9842763
Index 2, score=3.827115
Equation: -2.9764934 - (x5 * x5)

Index 8, score=0.969574
Equation: (sin((x1 * 1.9949355) + (x0 + -0.02534592)) - 2.9842763) - (x5 * x5)

Index 7, score=0.223452
Equation: (sin((sin(x1) * -2.7745197) + x0) - 2.9173124) - (x5 * x5)

## 5.5.3 Model 3

In [133]:
model_3_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.289
3           4.338e+03  1.665e-02  y = x₂ + -76.746
5           2.056e+00  3.827e+00  y = -2.9767 - (x₅ * x₅)
7           2.022e+00  8.427e-03  y = -2.9856 - (x₅ * (x₅ - 0.021677))
9           2.022e+00  4.032e-05  y = (x₅ * ((0.021394 - x₅) * 0.99981)) - 2.9996
11          1.965e+00  1.433e-02  y = (-2.6125 - (x₅ * x₅)) - sin(exp(x₅) + 0.58146)
12          1.936e+00  1.477e-02  y = (-2.9252 - (x₅ * x₅)) - sin(sin(sin(x₅ * -21.507)))
13          1.899e+00  1.946e-02  y = (-2.5112 - (x₅ * x₅)) - sin(sin(x₅ * -21.525) + 0.7392...
                                      8)
14          1.888e+00  5.485e-03  y = (-2.5112 - (x₅ * x₅)) - sin(sin(sin(x₅ * -21.525) + 0....
                                      73928))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142041_ljCZ5A\hall_of_fame.csv

PySRRegressor.equations_ = [
	   pick     score                                           equation  \
	0        0.000000                                          -76.28858
	1        0.016651                                     x2 + -76.74557
	2  >>>>  3.827115                             -2.9766607 - (x5 * x5)
	3        0.008427              -2.985569 - (x5 * (x5 - 0.021677263))
	4        0.000040  (x5 * ((0.021394253 - x5) * 0.9998063)) - 2.99...
	5        0.014328  (-2.612488 - (x5 * x5)) - sin(exp(x5) + 0.5814...
	6        0.014768  (-2.9251816 - (x5 * x5)) - sin(sin(sin(x5 * -2...
	7        0.019458  (-2.511226 - (x5 * x5)) - sin(sin(x5 * -21.524...
	8        0.005485  (-2.511226 - (x5 * x5)) - sin(sin(sin(x5 * -21...

	          loss  complexity
	0  4484.837400           1
	1  4337.941400           3
	2     2.056336           5
	3     2.021970           7
	4     2.021806           9
	5     1.964691          11
	6     1.935890          12
	7     1.898585          13
	8     1.888200          14
]

In [134]:
best_equation_3 = model_3_wide_range.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 2.9766607
Index 2, score=3.827115
Equation: -2.9766607 - (x5 * x5)

Index 7, score=0.019458
Equation: (-2.511226 - (x5 * x5)) - sin(sin(x5 * -21.524742) + 0.73928386)

Index 1, score=0.016651
Equation: x2 + -76.74557

## 5.5.4 Model 1 with noise std_dev 2 and 5

In [135]:
model_1_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_1_noisy = model_1_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.022
3           4.336e+03  1.655e-02  y = x₂ + -76.486
5           9.261e+00  3.074e+00  y = x₅ * (x₅ * -1.0195)
7           5.635e+00  2.484e-01  y = (x₅ * (x₅ * -0.99853)) + -2.8225
9           5.631e+00  3.751e-04  y = (((x₅ + -0.0077528) * x₅) * -0.99871) + -2.8121
11          5.541e+00  8.079e-03  y = (((x₅ * x₅) + sin(exp(x₄))) + 2.7311) * -0.99877
12          5.512e+00  5.086e-03  y = (((x₅ * x₅) + sin(x₅ * 0.91946)) * -0.9989) + -2.8963
13          5.316e+00  3.620e-02  y = ((sin(exp(x₅ + -2.0672)) + (x₅ * x₅)) + 2.8819) * -0.9...
                                      9745
17          5.270e+00  2.179e-03  y = ((sin((cos(x₀) * -1.6468) + x₅) + ((x₅ * x₅) + 1.5376)...
                                      ) * -0.99877) + -1.2223
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

Best by score: x5*x5*(-0.99852943) - 2.8224525
Index 2, score=3.074411
Equation: x5 * (x5 * -1.0195066)

Index 3, score=0.248400
Equation: (x5 * (x5 * -0.99852943)) + -2.8224525

Index 7, score=0.036203
Equation: ((sin(exp(x5 + -2.0672276)) + (x5 * x5)) + 2.881923) * -0.9974481

  - outputs\20250511_142043_LDW7j5\hall_of_fame.csv

In [136]:
model_1_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_1_noisy = model_1_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.133
3           4.394e+03  1.726e-02  y = x₂ + -76.594
5           2.874e+01  2.515e+00  y = (x₅ * -1.0227) * x₅
7           2.578e+01  5.427e-02  y = ((x₅ * x₅) * -1.0037) + -2.5485
9           2.573e+01  9.794e-04  y = ((x₅ * -1.0031) * (x₅ + 0.026667)) + -2.5847
10          2.532e+01  1.615e-02  y = (((x₅ * -1.0035) * x₅) + cos(x₄)) + -2.6164
11          2.495e+01  1.475e-02  y = ((x₅ * (x₅ * -1.003)) + (x₀ * 0.10008)) + -2.511
12          2.467e+01  1.131e-02  y = (sin(x₄ * x₅) + (x₅ * (x₅ * -1.004))) + -2.5133
13          2.465e+01  7.799e-04  y = (sin(exp(x₀ * 4.1096)) + -2.4091) + (x₅ * (x₅ * -1.004...
                                      6))
14          2.447e+01  7.303e-03  y = ((x₅ * (x₅ * -1.0041)) + (sin(x₄ * x₅) * 1.6366)) + -2...
                                      .491
15          2.443e+01  1.785e-03  y = (sin(sin(x₄ * x₅)) * 1.8832) + ((x₅ * (x₅ * -1.0042)) ...
                                      + -2.4791)
16          2.395e+01  1.984e-02  y = sin(x₄ * x₅) + (((x₀ * 0.093152) + -2.4782) + (x₅ * (x...
                                      ₅ * -1.0033)))
17          2.391e+01  1.490e-03  y = ((sin(x₀ * 0.13896) + -2.4368) + sin(x₄ * x₅)) + (x₅ *...
                                       (x₅ * -1.0038))
18          2.356e+01  1.493e-02  y = ((sin(x₄ * x₅) + -2.4091) + sin(exp(x₀ * 4.1096))) + (...
                                      (x₅ * x₅) * -1.0046)
20          2.346e+01  2.094e-03  y = ((x₅ * x₅) * -1.0038) + ((sin(x₅ * x₄) + -2.4785) + si...
                                      n(x₀ * (sin(x₂) * 4.0771)))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142044_CTxqPn\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

Best by score: x5*(-1.0226563)*x5
Index 2, score=2.514830
Equation: (x5 * -1.0226563) * x5

Index 3, score=0.054270
Equation: ((x5 * x5) * -1.0037116) + -2.5485175

Index 11, score=0.019837
Equation: sin(x4 * x5) + (((x0 * 0.093151584) + -2.4782333) + (x5 * (x5 * -1.003336)))

## 5.5.5 Model 2 with noise std_dev 2 and 5

In [137]:
model_2_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_2_noisy = model_2_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.022
3           4.336e+03  1.655e-02  y = x₂ + -76.483
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.624e-04  y = -2.8214 - (x₅ * (x₅ * 0.99853))
9           5.550e+00  7.634e-03  y = (-2.6838 - (x₅ * x₅)) - sin(exp(x₄))
10          5.159e+00  7.291e-02  y = (sin(x₀ * 1.4518) - (x₅ * x₅)) - 2.7658
12          5.142e+00  1.711e-03  y = (sin((x₀ + 0.13451) * 1.4556) - (x₅ * x₅)) - 2.7376
15          5.044e+00  6.411e-03  y = (sin((1.4518 * x₀) + sin(0.45525 - x₂)) - (x₅ * x₅)) -...
                                       2.7658
16          5.021e+00  4.569e-03  y = (sin((1.4518 * x₀) + sin(cos(-0.75302) - x₂)) - (x₅ * ...
                                      x₅)) - 2.7658
20          4.145e+00  4.792e-02  y = (cos(-0.15387 - ((x₀ + x₁) + ((x₁ + -0.24263) + -1.396...
                                      2))) - ((x₅ * x₅) + 2.173)) - 0.51793
21          3.926e+00  5.438e-02  y = (cos((0.89941 - cos(((x₀ + x₁) + x₁) + -1.6387)) * -1....
                                      8173) - ((x₅ * x₅) + 2.1736)) - 0.51827
23          3.926e+00  8.941e-08  y = (cos(-0.16204 - ((cos((x₀ + (x₁ + x₁)) + -1.6388) - 0....
                                      80997) * -1.8181)) - ((x₅ * x₅) + 1.9653)) - 0.72588
25          3.831e+00  1.218e-02  y = ((-0.070736 - ((cos(((x₀ + (x₁ + x₁)) + 0.089133) + -1...
                                      .7279) - sin(0.31207)) * -1.8182)) - ((x₅ * x₅) + 1.9653))...
                                       - 0.72579
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142047_Cc10AP\hall_of_fame.csv
Best by score: -x5*x5 - 2.7146323
Index 2, score=3.321948
Equation: -2.7146323 - (x5 * x5)

Index 5, score=0.072914
Equation: (sin(x0 * 1.4518161) - (x5 * x5)) - 2.7658126

Index 10, score=0.054379
Equation: (cos((0.8994098 - cos(((x0 + x1) + x1) + -1.6386757)) * -1.8172939) - ((x5 * x5) + 2.173646)) - 0.5182656

In [138]:
model_2_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_2_noisy = model_2_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.133
3           4.394e+03  1.726e-02  y = x₂ + -76.589
5           2.585e+01  2.568e+00  y = -2.8207 - (x₅ * x₅)
7           2.578e+01  1.385e-03  y = (x₅ * (-0.03127 - x₅)) + -2.8078
8           2.538e+01  1.561e-02  y = cos(x₄) + (-2.8704 - (x₅ * x₅))
9           2.485e+01  2.087e-02  y = -1.3804 - ((x₅ * x₅) + safe_pow(0.91706, x₀))
10          2.474e+01  4.457e-03  y = (-2.8031 - (x₅ * x₅)) + sin(x₅ * x₄)
12          2.461e+01  2.595e-03  y = -2.7615 - (sin((x₂ + 1.3828) * -6.3337) + (x₅ * x₅))
13          2.440e+01  8.546e-03  y = (x₀ * 0.095188) + ((sin(exp(x₁)) + -2.8336) - (x₅ * x₅...
                                      ))
15          2.425e+01  3.142e-03  y = ((-2.7078 - (x₅ * x₅)) + sin(exp(x₂ - 0.33092))) + (x₀...
                                       * 0.10022)
16          2.386e+01  1.613e-02  y = ((x₀ * 0.094288) + -2.6961) - ((x₅ * x₅) + sin((x₂ + 3...
                                      .383) * -6.333))
18          2.383e+01  5.967e-04  y = ((x₀ * 0.10702) + (-2.7211 - (x₅ * x₅))) + sin(x₂ + (x...
                                      ₄ - (x₅ * -9.6516)))
19          2.362e+01  9.169e-03  y = ((((-0.0038969 - x₅) * x₅) + -2.6525) + sin((x₅ * x₄) ...
                                      - sin(x₃))) + (x₀ * 0.093261)
21          2.353e+01  1.881e-03  y = ((sin((x₅ * x₄) - sin(x₃)) + ((-0.0038969 - x₅) * (x₅ ...
                                      + 0.034354))) + (x₀ * 0.093261)) + -2.6868
23          2.353e+01  2.980e-08  y = (((((x₅ + 0.037692) * (-0.00055939 - x₅)) + (x₀ * 0.09...
                                      326)) + -1.598) + sin((x₄ * x₅) - sin(x₃))) + -1.0888
24          2.342e+01  4.465e-03  y = (((x₅ + 1.5595) * (1.516 - x₅)) + (sin((-2.4803 + x₀) ...
                                      * 12.057) + -5.1165)) + sin((x₄ * x₅) - sin(x₃))
25          2.295e+01  2.062e-02  y = ((((x₅ + 2.0553) * (2.0237 - x₅)) + sin(x₅ * x₄)) + si...
                                      n(((x₀ + -2.474) * 17.355) + (x₅ * 0.33421))) + -6.9519
28          2.261e+01  4.884e-03  y = ((((x₅ + 1.5806) * (1.5511 - x₅)) + (x₀ * 0.0941)) + s...
                                      in((x₀ + -2.4971) * 12.09)) + (sin((x₄ * x₅) - sin(x₃)) + ...
                                      -5.0937)
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: -x5*x5 - 2.8206582
Index 2, score=2.567903
Equation: -2.8206582 - (x5 * x5)

Index 5, score=0.020870
Equation: -1.3804003 - ((x5 * x5) + safe_pow(0.91706187, x0))

Index 16, score=0.020620
Equation: ((((x5 + 2.0552676) * (2.0237021 - x5)) + sin(x5 * x4)) + sin(((x0 + -2.4739645) * 17.355097) + (x5 * 0.33420867))) + -6.9518814

  - outputs\20250511_142049_4NwMgG\hall_of_fame.csv

## 5.5.6 Model 3 with noise

In [139]:
model_3_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_3_noisy = model_3_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.022
3           4.336e+03  1.655e-02  y = x₂ + -76.491
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.625e-04  y = ((x₅ * x₅) * -0.99853) + -2.8235
9           5.631e+00  3.749e-04  y = (x₅ * ((x₅ * -0.99871) - -0.0077398)) + -2.8122
11          5.541e+00  8.060e-03  y = ((x₅ * (x₅ * -0.99878)) - sin(exp(x₄))) + -2.726
12          5.344e+00  3.612e-02  y = ((x₅ * x₅) * -0.99824) - (sin(x₅ * 6.6642) + 2.9024)
13          5.194e+00  2.860e-02  y = (((x₅ * x₅) * -0.99761) - 2.9992) + sin(exp(x₅ * 0.931...
                                      13))
15          5.193e+00  1.591e-05  y = ((((x₅ * x₅) * -0.99761) - 2.9992) + sin(exp(x₅ * 0.93...
                                      113))) - -0.023546
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142052_0PYPuc\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

Best by score: -x5*x5 - 2.7146323
Index 2, score=3.321948
Equation: -2.7146323 - (x5 * x5)

Index 6, score=0.036115
Equation: ((x5 * x5) * -0.99824184) - (sin(x5 * 6.66415) + 2.9024115)

Index 7, score=0.028596
Equation: (((x5 * x5) * -0.9976149) - 2.9991846) + sin(exp(x5 * 0.93113196))

In [140]:
model_3_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_3_noisy = model_3_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.133
3           4.394e+03  1.726e-02  y = x₂ - 76.589
5           2.585e+01  2.568e+00  y = -2.8207 - (x₅ * x₅)
7           2.578e+01  1.385e-03  y = ((-0.03127 - x₅) * x₅) + -2.8076
9           2.499e+01  1.541e-02  y = (x₀ * 0.10113) - ((x₅ * x₅) + 2.7326)
10          2.474e+01  1.011e-02  y = sin(x₅ * x₄) + (-2.8038 - (x₅ * x₅))
12          2.464e+01  2.015e-03  y = sin(x₅ * x₄) + ((x₅ * (-0.036889 - x₅)) - 2.7884)
13          2.441e+01  9.510e-03  y = sin((sin(x₂) * x₄) * x₂) + (-2.775 - (x₅ * x₅))
15          2.437e+01  7.558e-04  y = sin(sin(x₂) * (x₄ * x₂)) + ((x₅ * (-0.022403 - x₅)) - ...
                                      2.7526)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142054_lIAkHv\hall_of_fame.csv
Best by score: -x5*x5 - 2.820656
Index 2, score=2.567903
Equation: -2.820656 - (x5 * x5)

Index 1, score=0.017257
Equation: x2 - 76.58875

Index 4, score=0.015413
Equation: (x0 * 0.10113394) - ((x5 * x5) + 2.7325895)

# 5.6 Output into a DF [4.0]

In [141]:
import pandas as pd

data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5'   
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1,best,(x5*x5 + 3.1199038)*(-0.9900283) + cos(x0 + x1...,2.031154
1,model_1,3,x5 * (x5 * -1.1931313),2.031154
2,model_1,4,((x5 * x5) * -0.9815453) + -3.163114,0.560019
3,model_1,10,cos(x1 + (x0 + (x1 + -1.5520582))) + (((x5 * x...,0.548707
4,model_2,best,-x5*x5 - 3.0129306,3.142667
5,model_2,3,-3.0129306 - (x5 * x5),3.142667
6,model_2,2,cos(x5) + -10.987488,0.072084
7,model_2,8,cos(cos(x1 + cos(x0))) + (-3.8053768 - (x5 * x5)),0.063031
8,model_3,best,-x5*x5 - 3.0142558,3.201108
9,model_3,3,-3.0142558 - (x5 * x5),3.201108
10,model_3,10,((x5 * x5) * -0.97893745) + (-3.816306 - sin(-...,0.015979
11,model_3,2,-11.1574 - sin(x0),0.013642
12,model_1_noisy,best,x5*x5*(-0.9798251) - 3.1116428,2.018258
13,model_1_noisy,3,(x5 * -1.1879656) * x5,2.018258
14,model_1_noisy,4,((x5 * x5) * -0.9798251) + -3.1116428,0.514755
15,model_1_noisy,2,cos(x5) + -10.9218025,0.074934
16,model_2_noisy,best,-x5*x5 - 2.9473078,3.038596
17,model_2_noisy,3,-2.9473078 - (x5 * x5),3.038596
18,model_2_noisy,9,"(safe_pow(x5 * x5, 1.0510213) * -0.82659906) +...",0.086357
19,model_2_noisy,2,cos(x5) + -10.922012,0.069191
20,model_3_noisy,best,-x5*x5 - 2.9474645,3.096697
21,model_3_noisy,3,-2.9474645 - (x5 * x5),3.096697
22,model_3_noisy,6,(x5 * ((x4 * 0.036646537) + (x5 * -0.97839344)...,0.014852
23,model_3_noisy,2,-11.0919695 - sin(x0),0.011090
24,model_1_wide_range,best,x5*x5*(-0.9992923) - 3.0284927,3.273026
25,model_1_wide_range,2,x5 * (x5 * -1.0218015),3.273026
26,model_1_wide_range,3,(x5 * (x5 * -0.9992923)) + -3.0284927,0.554636
27,model_1_wide_range,7,(sin(x0 * -1.4146291) + (((x5 * x5) * 1.677411...,0.037771
28,model_2_wide_range,best,-x5*x5 + sin(x0 + x1*1.9949355 - 0.02534592) -...,3.827115
29,model_2_wide_range,2,-2.9764934 - (x5 * x5),3.827115
30,model_2_wide_range,8,(sin((x1 * 1.9949355) + (x0 + -0.02534592)) - ...,0.969574
31,model_2_wide_range,7,(sin((sin(x1) * -2.7745197) + x0) - 2.9173124)...,0.223452
32,model_3_wide_range,best,-x5*x5 - 2.9766607,3.827115
33,model_3_wide_range,2,-2.9766607 - (x5 * x5),3.827115
34,model_3_wide_range,7,(-2.511226 - (x5 * x5)) - sin(sin(x5 * -21.524...,0.019458
35,model_3_wide_range,1,x2 + -76.74557,0.016651
36,model_1_noisy_std_dev_2,best,x5*x5*(-0.99852943) - 2.8224525,3.074411
37,model_1_noisy_std_dev_2,2,x5 * (x5 * -1.0195066),3.074411
38,model_1_noisy_std_dev_2,3,(x5 * (x5 * -0.99852943)) + -2.8224525,0.248400
39,model_1_noisy_std_dev_2,7,((sin(exp(x5 + -2.0672276)) + (x5 * x5)) + 2.8...,0.036203
40,model_2_noisy_std_dev_2,best,-x5*x5 - 2.7146323,3.321948
41,model_2_noisy_std_dev_2,2,-2.7146323 - (x5 * x5),3.321948
42,model_2_noisy_std_dev_2,5,(sin(x0 * 1.4518161) - (x5 * x5)) - 2.7658126,0.072914
43,model_2_noisy_std_dev_2,10,(cos((0.8994098 - cos(((x0 + x1) + x1) + -1.63...,0.054379
44,model_3_noisy_std_dev_2,best,-x5*x5 - 2.7146323,3.321948
45,model_3_noisy_std_dev_2,2,-2.7146323 - (x5 * x5),3.321948
46,model_3_noisy_std_dev_2,6,((x5 * x5) * -0.99824184) - (sin(x5 * 6.66415)...,0.036115
47,model_3_noisy_std_dev_2,7,(((x5 * x5) * -0.9976149) - 2.9991846) + sin(e...,0.028596
48,model_1_noisy_std_dev_5,best,x5*(-1.0226563)*x5,2.514830
49,model_1_noisy_std_dev_5,2,(x5 * -1.0226563) * x5,2.514830
50,model_1_noisy_std_dev_5,3,((x5 * x5) * -1.0037116) + -2.5485175,0.054270
51,model_1_noisy_std_dev_5,11,sin(x4 * x5) + (((x0 * 0.093151584) + -2.47823...,0.019837
52,model_2_noisy_std_dev_5,best,-x5*x5 - 2.8206582,2.567903
53,model_2_noisy_std_dev_5,2,-2.8206582 - (x5 * x5),2.567903
54,model_2_noisy_std_dev_5,5,"-1.3804003 - ((x5 * x5) + safe_pow(0.91706187,...",0.020870
55,model_2_noisy_std_dev_5,16,((((x5 + 2.0552676) * (2.0237021 - x5)) + sin(...,0.020620
56,model_3_noisy_std_dev_5,best,-x5*x5 - 2.820656,2.567903
57,model_3_noisy_std_dev_5,2,-2.820656 - (x5 * x5),2.567903
58,model_3_noisy_std_dev_5,1,x2 - 76.58875,0.017257
59,model_3_noisy_std_dev_5,4,(x0 * 0.10113394) - ((x5 * x5) + 2.7325895),0.015413

In [142]:
df.to_csv('results4.csv')

In [143]:
data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5'   
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

In [144]:
df.to_csv('results4_only_best.csv')

# 5.7 Function f [5.0]

$$f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$$

- X (random values  $\mathbb{R}^6$ [-5, 5])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev = 0.5)

In [145]:
import numpy as np
from pysr import PySRRegressor
from math import sin
import sympy

np.random.seed(0)
X = np.random.uniform(-5, 5, size=(200, 6))


from sympy import primerange
primes_list = [0] + list(primerange(1, 1000))
primes_dict = {i: primes_list[i] if i < len(primes_list) else 0 for i in range(1000)}

y = [
    2.2 * sin(X[i, 0] + 2 * X[i, 1]) - X[i, 5] ** 2 - primes_dict[abs(int(X[i, 0]))]
    for i in range(200)
]

# Dodaj szum
noise = np.random.normal(loc=0.0, scale=0.5, size=200)
y_noisy = np.array(y) + noise

In [146]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

# 5.8 Experiments [5.0]

## 5.8.1 Model 1

In [147]:
import sympy
class sympy_p(sympy.Function):
    pass

model_1f = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    extra_sympy_mappings={"p": sympy_p},
    maxsize=20,
    **default_pysr_params,
)

model_1f_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    extra_sympy_mappings={"p": sympy_p},
    timeout_in_seconds=60,
    maxsize=20,
    **default_pysr_params,
)

model_1f.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           6.176e+01  1.594e+01  y = -11.904
3           6.118e+01  4.750e-03  y = x₂ + -12.055
4           5.765e+01  5.949e-02  y = cos(x₅) + -11.732
5           1.548e+01  1.315e+00  y = (x₅ * x₅) * -1.2424
7           8.495e+00  3.000e-01  y = (x₅ * (x₅ * -0.98039)) + -3.9176
9           8.481e+00  8.454e-04  y = (((x₅ * -0.9773) + -0.042789) * x₅) + -3.9368
10          7.420e+00  1.335e-01  y = ((x₅ * -0.98748) * x₅) + (cos(x₀) + -3.5919)
11          6.738e+00  9.646e-02  y = (p(cos(x₀)) + -4.1558) + (x₅ * (x₅ * -0.99042))
12          5.588e+00  1.871e-01  y = (x₅ * (x₅ * -0.97893)) + (cos(x₀ * 0.6565) + -3.7816)
13          5.068e+00  9.772e-02  y = (((x₅ * x₅) * -0.97568) + -5.0463) + p(cos(x₀ * 0.3452...
                                      3))
14          4.098e+00  2.125e-01  y = ((x₅ * x₅) * -0.97193) + (p(p(cos(x₀ * 0.3449))) + -5....
                                      6105)
17          3.688e+00  3.512e-02  y = ((x₅ * -0.97892) * x₅) + (cos(x₀ * 0.6565) + (cos(x₀ *...
                                       0.6565) + -3.7816))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142056_2plWoe\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.903739
	1         0.004750                                    x2 + -12.055384
	2         0.059494                               cos(x5) + -11.732317
	3         1.314799                             (x5 * x5) * -1.2424467
	4         0.300026             (x5 * (x5 * -0.98038584)) + -3.9175878
	5         0.000846  (((x5 * -0.9773026) + -0.04278874) * x5) + -3....
	6         0.133550  ((x5 * -0.9874798) * x5) + (cos(x0) + -3.5919144)
	7         0.096457  (p(cos(x0)) + -4.155809) + (x5 * (x5 * -0.9904...
	8         0.187139  (x5 * (x5 * -0.9789275)) + (cos(x0 * 0.6564984...
	9         0.097718  (((x5 * x5) * -0.97568095) + -5.0463343) + p(c...
	10  >>>>  0.212538  ((x5 * x5) * -0.9719317) + (p(p(cos(x0 * 0.344...
	11        0.035120  ((x5 * -0.9789228) * x5) + (cos(x0 * 0.6564984...

	         loss  complexity
	0   61.764057           1
	1   61.180126           3
	2   57.646427           4
	3   15.479691           5
	4    8.494999           7
	5    8.480646           9
	6    7.420428          10
	7    6.738115          11
	8    5.588109          12
	9    5.067880          13
	10   4.097529          14
	11   3.687782          17
]

### Model 1 best + top3 according to score

In [148]:
best_equation_1 = model_1f.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1f.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x5*x5*(-0.9719317) + sympy_p(sympy_p(cos(x0*0.34489843))) - 5.610484
Index 3, score=1.314799
Equation: (x5 * x5) * -1.2424467

Index 4, score=0.300026
Equation: (x5 * (x5 * -0.98038584)) + -3.9175878

Index 10, score=0.212538
Equation: ((x5 * x5) * -0.9719317) + (p(p(cos(x0 * 0.34489843))) + -5.610484)

## 5.8.2 Model 2

Added constraint to operator "^" - safe_pow

In [149]:
def safe_pow(x, y):
    if x < 0 and np.floor(y) != y:
        return np.nan
    return np.power(x, y)

model_2f = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=30,
    **default_pysr_params,
)

model_2f_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=30,
    **default_pysr_params,
)

model_2f.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           6.176e+01  1.594e+01  y = -11.904
3           6.118e+01  4.750e-03  y = x₂ + -12.055
4           4.339e+01  3.435e-01  y = -9.5186 - p(x₅)
5           8.516e+00  1.628e+00  y = -3.7578 - (x₅ * x₅)
7           8.495e+00  1.253e-03  y = ((x₅ * -0.98039) * x₅) - 3.9175
8           5.584e+00  4.196e-01  y = (x₀ - p(x₀)) - (x₅ * x₅)
9           2.736e+00  7.135e-01  y = ((x₀ * x₀) * -0.37088) - (x₅ * x₅)
11          2.525e+00  4.011e-02  y = ((x₀ * -0.32361) * x₀) + (-0.71698 - (x₅ * x₅))
13          2.503e+00  4.416e-03  y = (((x₀ + -0.15052) * x₀) * -0.32361) + (-0.71698 - (x₅ ...
                                      * x₅))
14          2.446e+00  2.290e-02  y = ((sin(x₀) + (x₀ * x₀)) * -0.32318) - ((x₅ * x₅) - -0.6...
                                      8476)
16          2.443e+00  5.972e-04  y = (((sin(x₀) - (x₀ * (0.15246 - x₀))) * -0.32354) - (x₅ ...
                                      * x₅)) - 0.71389
18          2.387e+00  1.166e-02  y = (((x₀ * x₀) + sin(x₀ + -0.83652)) * -0.31907) + ((-1.0...
                                      03 - (x₅ * x₅)) + 0.2931)
22          2.385e+00  2.009e-04  y = ((((x₀ * x₀) + sin(x₀ + -0.83204)) * -0.3186) + -0.525...
                                      42) + (safe_pow(1.0165, x₄) + (-1.1912 - (x₅ * x₅)))
23          2.338e+00  2.003e-02  y = (((x₀ * x₀) + sin(x₀)) * -0.3265) + (((-1.1572 - (x₅ *...
                                       x₅)) - sin(1.771 - (x₅ * 0.32985))) + 1.0582)
24          2.330e+00  3.270e-03  y = (((x₅ * x₅) * -0.9628) - ((((sin(sin(sin(x₀ + 2.4504))...
                                      ) - (x₀ * x₀)) + 2.6829) * -0.32297) + 1.2458)) + -0.61867
26          2.329e+00  2.817e-04  y = ((x₅ * x₅) * -0.96298) - (((((sin(sin(sin(x₀ + 2.4448)...
                                      )) - (x₀ * x₀)) + 2.2673) - (x₄ * -0.04207)) * -0.32255) +...
                                       1.7316)
28          2.320e+00  1.786e-03  y = (((x₅ * x₅) * -0.9628) - ((((sin(sin(x₀ + 2.4504)) - (...
                                      x₀ * x₀)) + (2.6829 - (x₄ * sin(-0.039911)))) * -0.32297) ...
                                      + 1.2458)) + -0.61867
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.903521
	1         0.004750                                    x2 + -12.055443
	2         0.343521                                  -9.518607 - p(x5)
	3         1.628317                             -3.7577968 - (x5 * x5)
	4         0.001253              ((x5 * -0.98039037) * x5) - 3.9175248
	5         0.419552                           (x0 - p(x0)) - (x5 * x5)
	6   >>>>  0.713500              ((x0 * x0) * -0.37088263) - (x5 * x5)
	7         0.040113  ((x0 * -0.32360584) * x0) + (-0.7169804 - (x5 ...
	8         0.004416  (((x0 + -0.15051766) * x0) * -0.32360584) + (-...
	9         0.022895  ((sin(x0) + (x0 * x0)) * -0.32318175) - ((x5 *...
	10        0.000597  (((sin(x0) - (x0 * (0.15245523 - x0))) * -0.32...
	11        0.011662  (((x0 * x0) + sin(x0 + -0.8365217)) * -0.31906...
	12        0.000201  ((((x0 * x0) + sin(x0 + -0.8320442)) * -0.3185...
	13        0.020027  (((x0 * x0) + sin(x0)) * -0.32649836) + (((-1....
	14        0.003270  (((x5 * x5) * -0.96279657) - ((((sin(sin(sin(x...
	15        0.000282  ((x5 * x5) * -0.9629762) - (((((sin(sin(sin(x0...
	16        0.001786  (((x5 * x5) * -0.96279657) - ((((sin(sin(x0 + ...

	         loss  complexity
	0   61.764057           1
	1   61.180126           3
	2   43.393124           4
	3    8.516313           5
	4    8.494999           7
	5    5.584111           8
	6    2.735805           9
	7    2.524898          11
	8    2.502695          13
	9    2.446046          14
	10   2.443126          16
	11   2.386802          18
	12   2.384885          22
	13   2.337597          23
	14   2.329965          24
	15   2.328653          26
	16   2.320349          28
]

  - outputs\20250511_142059_Kg8TTv\hall_of_fame.csv

In [150]:
best_equation_2 = model_2f.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2f.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x0*x0*(-0.37088263) - x5*x5
Index 3, score=1.628317
Equation: -3.7577968 - (x5 * x5)

Index 6, score=0.713500
Equation: ((x0 * x0) * -0.37088263) - (x5 * x5)

Index 5, score=0.419552
Equation: (x0 - p(x0)) - (x5 * x5)

## 5.8.3 Model 3

In [151]:
model_3f = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=15,
    **default_pysr_params,
)

model_3f_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=15,
    **default_pysr_params,
)

model_3f.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           6.176e+01  1.594e+01  y = -11.903
3           6.118e+01  4.750e-03  y = x₂ + -12.056
4           4.339e+01  3.435e-01  y = -9.5185 - p(x₅)
5           8.516e+00  1.628e+00  y = -3.758 - (x₅ * x₅)
7           8.495e+00  1.253e-03  y = ((x₅ * -0.98039) * x₅) + -3.9175
8           5.584e+00  4.196e-01  y = (x₀ - (x₅ * x₅)) - p(x₀)
10          4.076e+00  1.575e-01  y = (x₀ - (x₅ * x₅)) - (p(x₀) + 1.2283)
11          2.525e+00  4.789e-01  y = (-0.73067 - (x₅ * x₅)) - ((x₀ * x₀) * 0.32365)
13          2.450e+00  1.502e-02  y = ((-1.0514 - (x₅ * x₅)) - ((x₀ * x₀) * 0.33794)) * 0.96...
                                      324
14          2.443e+00  2.655e-03  y = (-0.7255 - (x₅ * x₅)) - (((x₀ * x₀) + sin(x₀)) * 0.324...
                                      17)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142104_hKPlBK\hall_of_fame.csv

PySRRegressor.equations_ = [
	   pick     score                                           equation  \
	0        0.000000                                         -11.903401
	1        0.004750                                     x2 + -12.05577
	2        0.343521                                  -9.518542 - p(x5)
	3        1.628317                             -3.7579765 - (x5 * x5)
	4        0.001253               ((x5 * -0.980391) * x5) + -3.9175193
	5        0.419552                           (x0 - (x5 * x5)) - p(x0)
	6        0.157456             (x0 - (x5 * x5)) - (p(x0) + 1.2282913)
	7  >>>>  0.478892  (-0.73067176 - (x5 * x5)) - ((x0 * x0) * 0.323...
	8        0.015018  ((-1.0513654 - (x5 * x5)) - ((x0 * x0) * 0.337...
	9        0.002655  (-0.72550035 - (x5 * x5)) - (((x0 * x0) + sin(...

	        loss  complexity
	0  61.764057           1
	1  61.180126           3
	2  43.393124           4
	3   8.516313           5
	4   8.494999           7
	5   5.584111           8
	6   4.075583          10
	7   2.524698          11
	8   2.449993          13
	9   2.443496          14
]

In [152]:
best_equation_3 = model_3f.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3f.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -0.3236481*x0*x0 - x5*x5 - 0.73067176
Index 3, score=1.628317
Equation: -3.7579765 - (x5 * x5)

Index 7, score=0.478892
Equation: (-0.73067176 - (x5 * x5)) - ((x0 * x0) * 0.3236481)

Index 5, score=0.419552
Equation: (x0 - (x5 * x5)) - p(x0)

## 5.8.4 Model 1 with noise

In [153]:
model_1f_noisy.fit(X, y_noisy)
best_equation_1_noisy = model_1f_noisy.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1f_noisy.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           6.161e+01  1.594e+01  y = -11.838
3           6.111e+01  4.091e-03  y = x₂ + -11.99
4           5.750e+01  6.084e-02  y = cos(x₅) + -11.667
5           1.533e+01  1.322e+00  y = (x₅ * -1.2373) * x₅
7           8.531e+00  2.932e-01  y = ((x₅ * x₅) + 3.9504) * -0.97867
9           8.509e+00  1.293e-03  y = ((x₅ * -0.97484) * (x₅ + 0.054393)) + -3.8899
10          7.496e+00  1.268e-01  y = (x₅ * (x₅ * -0.98576)) + (cos(x₀) + -3.5404)
11          7.123e+00  5.105e-02  y = ((x₅ * -0.98897) * x₅) + (exp(cos(x₀)) + -4.7289)
12          5.673e+00  2.276e-01  y = (x₅ * (x₅ * -0.97718)) + (cos(x₀ * 0.65472) + -3.733)
14          3.595e+00  2.281e-01  y = ((x₅ * (x₅ * -0.45216)) + (cos(x₀ * 0.60279) + -1.7497...
                                      )) * 2.1622
16          2.540e+00  1.736e-01  y = (((x₅ * (x₅ + 0.059037)) * -0.11559) + (cos(x₀ * 0.305...
                                      41) + -1.0966)) * 8.2998
18          2.525e+00  3.021e-03  y = (((x₅ * ((x₅ * -0.18044) + -0.01021)) + (cos(x₀ * 0.40...
                                      883) + -0.68939)) + -0.43264) * 5.3263
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142107_KlR4so\hall_of_fame.csv
Best by score: (x5*x5*(-0.45215756) + cos(x0*0.6027875) - 1.7497363)*2.1622398
Index 3, score=1.321810
Equation: (x5 * -1.2372673) * x5

Index 4, score=0.293151
Equation: ((x5 * x5) + 3.9503582) * -0.9786689

Index 9, score=0.228080
Equation: ((x5 * (x5 * -0.45215756)) + (cos(x0 * 0.6027875) + -1.7497363)) * 2.1622398

## 5.8.5 Model 2 with noise

In [154]:
model_2f_noisy.fit(X, y_noisy)
best_equation_2_noisy = model_2f_noisy.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2f_noisy.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           6.161e+01  1.594e+01  y = -11.837
3           6.109e+01  4.286e-03  y = -11.699 - x₅
4           4.305e+01  3.500e-01  y = -9.4541 - p(x₅)
5           8.557e+00  1.616e+00  y = -3.6923 - (x₅ * x₅)
7           8.531e+00  1.476e-03  y = (-3.9503 - (x₅ * x₅)) * 0.97867
8           7.507e+00  1.279e-01  y = (-3.4245 - (x₅ * x₅)) + cos(x₀)
10          5.702e+00  1.375e-01  y = (cos(x₀ * -0.65598) + -3.5452) - (x₅ * x₅)
11          2.694e+00  7.498e-01  y = -0.69794 - ((x₅ * x₅) + ((x₀ * x₀) * 0.32015))
13          2.684e+00  1.823e-03  y = (x₅ * (-0.03474 - x₅)) + (((x₀ * -0.32005) * x₀) + -0....
                                      69412)
14          2.676e+00  2.867e-03  y = (cos(x₀) - ((x₅ * x₅) + ((x₀ * x₀) * 0.29061))) + -0.7...
                                      0637
15          2.613e+00  2.405e-02  y = log(exp((-0.99166 - (x₅ * (x₅ * 0.9617))) + ((x₀ * x₀)...
                                       * -0.3221)))
17          2.586e+00  5.191e-03  y = log(exp((-0.98491 - (x₅ * (x₅ * 0.9606))) + ((x₀ * (x₀...
                                       + -0.1677)) * -0.32211)))
18          2.586e+00  8.750e-05  y = log(sin(exp((-0.98197 - ((x₅ * x₅) * 0.96072)) + (x₀ *...
                                       ((x₀ + -0.16836) * -0.32222)))))
19          2.560e+00  9.985e-03  y = log(exp((((-0.06017 - x₅) * 0.95642) * x₅) + (((x₀ + -...
                                      0.17317) * x₀) * -0.32217))) - 1.01
20          2.535e+00  9.715e-03  y = log(exp(((-0.96392 - (x₅ * (x₅ * 0.96584))) - (cos(x₀)...
                                       * -0.47783)) + ((x₀ * -0.30778) * x₀)))
22          2.434e+00  2.038e-02  y = log(exp(((-0.99853 - ((x₅ * x₅) * 0.9615)) - (cos(-0.7...
                                      5338 - x₀) * -0.63974)) + ((x₀ * -0.30812) * x₀)))
25          2.402e+00  4.409e-03  y = log(exp((x₀ * (x₀ * -0.2995)) + (-1.0849 - (((x₅ * 0.9...
                                      5883) * x₅) - cos((-0.31998 - x₀) - sin(exp(p(x₅))))))))
27          2.392e+00  2.004e-03  y = log(exp(((x₀ * (x₀ * -0.30581)) + -1.021) - ((x₅ * (x₅...
                                       * 0.95662)) - cos((-0.17519 - (x₀ * 1.0305)) - sin(exp(p(...
                                      x₅)))))))
28          2.067e+00  1.461e-01  y = log(exp((-0.84432 - (((x₅ * x₅) - cos(((0.060247 - x₀)...
                                       * 1.0527) - sin(p(exp(cos(x₁)))))) * 0.97459)) + ((x₀ * x...
                                      ₀) * -0.30308)))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142109_3TMFCC\hall_of_fame.csv
Best by score: -(x0*x0*0.32014713 + x5*x5) - 0.69793606
Index 3, score=1.615558
Equation: -3.6923122 - (x5 * x5)

Index 7, score=0.749810
Equation: -0.69793606 - ((x5 * x5) + ((x0 * x0) * 0.32014713))

Index 2, score=0.350048
Equation: -9.454115 - p(x5)

## 5.8.6 Model 3 with noise

In [155]:
model_3f_noisy.fit(X, y_noisy)
best_equation_3_noisy = model_3f_noisy.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3f_noisy.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           6.161e+01  1.594e+01  y = -11.838
3           6.109e+01  4.286e-03  y = -11.7 - x₅
4           4.305e+01  3.500e-01  y = -9.453 - p(x₅)
5           8.557e+00  1.616e+00  y = -3.6923 - (x₅ * x₅)
7           8.531e+00  1.476e-03  y = -3.866 - ((x₅ * x₅) * 0.97867)
8           5.579e+00  4.248e-01  y = (x₀ - p(x₀)) - (x₅ * x₅)
10          4.227e+00  1.388e-01  y = ((x₀ - p(x₀)) - (x₅ * x₅)) - 1.1628
12          3.484e+00  9.665e-02  y = (x₀ - p(x₀ * 1.0709)) - ((x₅ * x₅) - -0.97958)
13          3.181e+00  9.096e-02  y = ((x₀ * x₀) * (x₀ - (x₀ - -0.32014))) - (x₅ * x₅)
15          2.694e+00  8.312e-02  y = (x₀ * (x₀ * (x₀ - (x₀ - -0.32014)))) - ((x₅ * x₅) - -0...
                                      .69798)
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: x0 - (x5*x5 - 1*(-0.97957855)) - sympy_p(x0*1.0708553)
Index 3, score=1.615558
Equation: -3.6923122 - (x5 * x5)

Index 5, score=0.424775
Equation: (x0 - p(x0)) - (x5 * x5)

Index 2, score=0.350048
Equation: -9.453041 - p(x5)

  - outputs\20250511_142112_CjIJtF\hall_of_fame.csv

# 5.9 Output into a DF [5.0: 3.0]

In [156]:
import pandas as pd

data = []

for model_name in ['model_1f', 'model_2f', 'model_3f','model_1f_noisy', 'model_2f_noisy', 'model_3f_noisy']:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1f,best,x5*x5*(-0.9719317) + sympy_p(sympy_p(cos(x0*0....,1.314799
1,model_1f,3,(x5 * x5) * -1.2424467,1.314799
2,model_1f,4,(x5 * (x5 * -0.98038584)) + -3.9175878,0.300026
3,model_1f,10,((x5 * x5) * -0.9719317) + (p(p(cos(x0 * 0.344...,0.212538
4,model_2f,best,x0*x0*(-0.37088263) - x5*x5,1.628317
5,model_2f,3,-3.7577968 - (x5 * x5),1.628317
6,model_2f,6,((x0 * x0) * -0.37088263) - (x5 * x5),0.713500
7,model_2f,5,(x0 - p(x0)) - (x5 * x5),0.419552
8,model_3f,best,-0.3236481*x0*x0 - x5*x5 - 0.73067176,1.628317
9,model_3f,3,-3.7579765 - (x5 * x5),1.628317
10,model_3f,7,(-0.73067176 - (x5 * x5)) - ((x0 * x0) * 0.323...,0.478892
11,model_3f,5,(x0 - (x5 * x5)) - p(x0),0.419552
12,model_1f_noisy,best,(x5*x5*(-0.45215756) + cos(x0*0.6027875) - 1.7...,1.321810
13,model_1f_noisy,3,(x5 * -1.2372673) * x5,1.321810
14,model_1f_noisy,4,((x5 * x5) + 3.9503582) * -0.9786689,0.293151
15,model_1f_noisy,9,((x5 * (x5 * -0.45215756)) + (cos(x0 * 0.60278...,0.228080
16,model_2f_noisy,best,-(x0*x0*0.32014713 + x5*x5) - 0.69793606,1.615558
17,model_2f_noisy,3,-3.6923122 - (x5 * x5),1.615558
18,model_2f_noisy,7,-0.69793606 - ((x5 * x5) + ((x0 * x0) * 0.3201...,0.749810
19,model_2f_noisy,2,-9.454115 - p(x5),0.350048
20,model_3f_noisy,best,x0 - (x5*x5 - 1*(-0.97957855)) - sympy_p(x0*1....,1.615558
21,model_3f_noisy,3,-3.6923122 - (x5 * x5),1.615558
22,model_3f_noisy,5,(x0 - p(x0)) - (x5 * x5),0.424775
23,model_3f_noisy,2,-9.453041 - p(x5),0.350048

In [157]:
df.to_csv('results5_for3.csv')

# 5.10 Function f [5.0: 4.0]

$$f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$$

- X (random values  $\mathbb{R}^6$ [-15, 15])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev1 = 2, std_dev2 = 5)

In [158]:
from numpy import sin, cos, exp, log, sqrt
# Dataset

np.random.seed(0)
X = np.random.uniform(-15, 15, size=(200, 6))
# y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 2
from sympy import primerange
primes_list = [0] + list(primerange(1, 1000))
primes_dict = {i: primes_list[i] if i < len(primes_list) else 0 for i in range(1000)}

y = [
    2.2 * sin(X[i, 0] + 2 * X[i, 1]) - X[i, 5] ** 2 - primes_dict[abs(int(X[i, 0]))]
    for i in range(200)
]
# Add the y samples with random noise
noise1 = np.random.normal(loc=0.0, scale=2, size=len(y))
y_noisy1 = np.array(y) + noise1
noise2 = np.random.normal(loc=0.0, scale=5, size=len(y))
y_noisy2 = np.array(y) + noise2

In [159]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

# 5.11 Experiments [5.0]

## 5.11.1 Model 1

In [160]:
model_1f_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    extra_sympy_mappings={"p": sympy_p},
    maxsize=20,
    **default_pysr_params,
)

model_1f_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    extra_sympy_mappings={"p": sympy_p},
    maxsize=20,
    **default_pysr_params,
)

model_1f_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    extra_sympy_mappings={"p": sympy_p},
    maxsize=20,
    **default_pysr_params,
)

model_1f_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.740e+03  1.594e+01  y = -94.018
3           4.584e+03  1.665e-02  y = x₂ + -94.468
4           4.534e+03  1.100e-02  y = p(x₂) + -104.32
5           3.869e+02  2.461e+00  y = x₅ * (x₅ * -1.1565)
7           1.995e+02  3.312e-01  y = ((x₅ * x₅) + 20.18) * -1.0056
9           1.995e+02  3.952e-05  y = (x₅ * ((x₅ + -0.014939) * -1.006)) + -20.276
10          1.977e+02  9.030e-03  y = ((cos(x₀) + 20.22) + (x₅ * x₅)) * -1.0048
11          1.970e+02  3.316e-03  y = ((cos(p(x₁)) + 19.534) + (x₅ * x₅)) * -1.0058
12          6.860e+01  1.055e+00  y = ((x₅ * x₅) + 21.867) * (cos(x₀ * -0.053239) + -1.8729)
13          6.635e+01  3.329e-02  y = ((x₅ * x₅) + 21.908) * (cos(sin(x₀ * -0.06135)) + -1.8...
                                      606)
14          1.926e+01  1.237e+00  y = ((cos(x₀ * 0.037244) + -1.9345) * ((x₅ * x₅) + 185.54)...
                                      ) + 162.78
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142114_8SbLJ9\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                          -94.01773
	1         0.016655                                     x2 + -94.46812
	2         0.011004                                 p(x2) + -104.31716
	3         2.461164                             x5 * (x5 * -1.1564775)
	4         0.331178               ((x5 * x5) + 20.179605) * -1.0056341
	5         0.000040  (x5 * ((x5 + -0.014938698) * -1.0059801)) + -2...
	6         0.009030     ((cos(x0) + 20.22018) + (x5 * x5)) * -1.004757
	7         0.003316  ((cos(p(x1)) + 19.534197) + (x5 * x5)) * -1.00...
	8         1.055161  ((x5 * x5) + 21.867205) * (cos(x0 * -0.0532386...
	9         0.033289  ((x5 * x5) + 21.908077) * (cos(sin(x0 * -0.061...
	10  >>>>  1.237054  ((cos(x0 * 0.037244465) + -1.9344844) * ((x5 *...

	           loss  complexity
	0   4739.506300           1
	1   4584.237300           3
	2   4534.071000           4
	3    386.917400           5
	4    199.508210           7
	5    199.492420           9
	6    197.699070          10
	7    197.044570          11
	8     68.598360          12
	9     66.352390          13
	10    19.257977          14
]

### Model 1 best + top3 according to score

In [161]:
best_equation_1 = model_1f_wide_range.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1f_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: (x5*x5 + 185.54434)*(cos(x0*0.037244465) - 1.9344844) + 162.78224
Index 3, score=2.461164
Equation: x5 * (x5 * -1.1564775)

Index 10, score=1.237054
Equation: ((cos(x0 * 0.037244465) + -1.9344844) * ((x5 * x5) + 185.54434)) + 162.78224

Index 8, score=1.055161
Equation: ((x5 * x5) + 21.867205) * (cos(x0 * -0.053238675) + -1.8729187)

## 5.11.2 Model 2

Added constraint to operator "^" - safe_pow

In [162]:
def safe_pow(x, y):
    if x < 0 and np.floor(y) != y:
        return np.nan
    return np.power(x, y)

model_2f_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=30,
    **default_pysr_params,
)

model_2f_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=30,
    **default_pysr_params,
)

model_2f_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=30,
    **default_pysr_params,
)

model_2f_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.740e+03  1.594e+01  y = -94.018
3           4.584e+03  1.665e-02  y = x₂ + -94.481
4           3.698e+03  2.149e-01  y = -83.179 - p(x₅)
5           1.997e+02  2.919e+00  y = -20.707 - (x₅ * x₅)
7           1.995e+02  3.588e-04  y = (x₅ * (x₅ * -1.0056)) + -20.293
8           1.667e+02  1.797e-01  y = x₀ - ((x₅ * x₅) + p(x₀))
10          6.971e+01  4.359e-01  y = x₀ + (-9.8485 - ((x₅ * x₅) + p(x₀)))
12          3.887e+01  2.921e-01  y = (x₀ * 2.3359) - ((x₅ * x₅) + p(x₀ - -4.4075))
13          1.673e+01  8.427e-01  y = ((x₀ * 2.8866) - ((x₅ * x₅) + p(x₀))) - p(x₀)
15          1.356e+01  1.051e-01  y = ((x₀ * 2.8865) + (1.7811 - ((x₅ * x₅) + p(x₀)))) - p(x...
                                      ₀)
17          4.532e+00  5.480e-01  y = (((x₀ * 4.1625) + 15.086) - p(x₀ + 6.5043)) - (p(x₀) +...
                                       (x₅ * x₅))
19          4.436e+00  1.074e-02  y = (((x₀ * 4.1584) + 8.0061) + (7.247 - p(x₀ + 6.4982))) ...
                                      - (p(x₀) + (x₅ * x₅))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142117_LUpQxA\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -94.017784
	1         0.016655                                     x2 + -94.48098
	2         0.214858                                  -83.17912 - p(x5)
	3         2.918948                             -20.706505 - (x5 * x5)
	4         0.000359              (x5 * (x5 * -1.0056481)) + -20.292583
	5         0.179696                           x0 - ((x5 * x5) + p(x0))
	6         0.435887             x0 + (-9.848491 - ((x5 * x5) + p(x0)))
	7         0.292135  (x0 * 2.3359368) - ((x5 * x5) + p(x0 - -4.40751))
	8         0.842747   ((x0 * 2.8865676) - ((x5 * x5) + p(x0))) - p(x0)
	9         0.105093  ((x0 * 2.886549) + (1.7810879 - ((x5 * x5) + p...
	10  >>>>  0.547972  (((x0 * 4.162522) + 15.086409) - p(x0 + 6.5042...
	11        0.010736  (((x0 * 4.158403) + 8.006145) + (7.2470417 - p...

	           loss  complexity
	0   4739.506300           1
	1   4584.237000           3
	2   3697.901400           4
	3    199.651460           5
	4    199.508210           7
	5    166.694000           8
	6     69.712970          10
	7     38.865900          12
	8     16.732790          13
	9     13.560814          15
	10     4.532347          17
	11     4.436068          19
]

In [163]:
best_equation_2 = model_2f_wide_range.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2f_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x0*4.162522 - (x5*x5 + sympy_p(x0)) - sympy_p(x0 + 6.504262) + 15.086409
Index 3, score=2.918948
Equation: -20.706505 - (x5 * x5)

Index 8, score=0.842747
Equation: ((x0 * 2.8865676) - ((x5 * x5) + p(x0))) - p(x0)

Index 10, score=0.547972
Equation: (((x0 * 4.162522) + 15.086409) - p(x0 + 6.504262)) - (p(x0) + (x5 * x5))

## 5.11.3 Model 3

In [164]:
model_3f_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=15,
    **default_pysr_params,
)

model_3f_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=15,
    **default_pysr_params,
)

model_3f_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin", "p"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y), "p": sympy_p},
    maxsize=15,
    **default_pysr_params,
)

model_3f_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.740e+03  1.594e+01  y = -94.018
3           4.584e+03  1.665e-02  y = x₂ + -94.476
4           3.698e+03  2.149e-01  y = -83.176 - p(x₅)
5           1.997e+02  2.919e+00  y = -20.707 - (x₅ * x₅)
7           1.995e+02  3.589e-04  y = ((x₅ * x₅) * -1.0056) - 20.292
8           1.667e+02  1.797e-01  y = x₀ - ((x₅ * x₅) + p(x₀))
10          6.971e+01  4.359e-01  y = ((x₀ + -9.8479) - (x₅ * x₅)) - p(x₀)
12          6.837e+01  9.739e-03  y = ((((x₅ * x₅) - x₀) * -1.017) - p(x₀)) + -8.5841
14          4.548e+01  2.038e-01  y = (x₀ + (((x₅ * x₅) - x₀) * -1.0368)) - p(x₀ + 3.3881)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142121_spyS2t\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	   pick     score                                           equation  \
	0        0.000000                                          -94.01775
	1        0.016655                                     x2 + -94.47609
	2        0.214858                                  -83.17635 - p(x5)
	3        2.918947                             -20.706514 - (x5 * x5)
	4        0.000359               ((x5 * x5) * -1.0056343) - 20.292253
	5        0.179695                           x0 - ((x5 * x5) + p(x0))
	6        0.435887             ((x0 + -9.847924) - (x5 * x5)) - p(x0)
	7        0.009739  ((((x5 * x5) - x0) * -1.0170372) - p(x0)) + -8...
	8  >>>>  0.203826  (x0 + (((x5 * x5) - x0) * -1.0368098)) - p(x0 ...

	          loss  complexity
	0  4739.506300           1
	1  4584.237300           3
	2  3697.901000           4
	3   199.651460           5
	4   199.508180           7
	5   166.694000           8
	6    69.712980          10
	7    68.368220          12
	8    45.479248          14
]

In [165]:
best_equation_3 = model_3f_wide_range.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3f_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x0 + (-x0 + x5*x5)*(-1.0368098) - sympy_p(x0 + 3.3880653)
Index 3, score=2.918947
Equation: -20.706514 - (x5 * x5)

Index 6, score=0.435887
Equation: ((x0 + -9.847924) - (x5 * x5)) - p(x0)

Index 2, score=0.214858
Equation: -83.17635 - p(x5)

## 5.11.4 Model 1 with noise std_dev 2 and 5

In [166]:
model_1f_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_1_noisy = model_1f_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1f_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.733e+03  1.594e+01  y = -93.756
3           4.579e+03  1.657e-02  y = x₂ + -94.213
4           4.528e+03  1.121e-02  y = -103.53 + p(x₂)
5           3.836e+02  2.468e+00  y = (x₅ * x₅) * -1.1542
7           2.000e+02  3.257e-01  y = ((x₅ * x₅) * -1.0049) + -20.086
9           2.000e+02  2.384e-07  y = ((x₅ * (x₅ + -0.001308)) * -1.0049) + -20.084
10          1.979e+02  1.032e-02  y = (((x₅ * x₅) + sin(x₅)) * -1.0042) + -20.196
11          1.348e+01  2.687e+00  y = (((x₀ * x₀) * 0.21902) + (x₅ * x₅)) * -1.0104
13          9.500e+00  1.749e-01  y = ((x₀ * x₀) * -0.20302) + (((x₅ * x₅) * -0.99419) + -3....
                                      781)
15          9.387e+00  6.006e-03  y = (((x₀ * (x₀ + -0.18213)) * -0.20302) + ((x₅ * x₅) * -0...
                                      .99394)) + -3.7668
17          9.385e+00  8.330e-05  y = (((x₀ * (x₀ + -0.18251)) * -0.20303) + (x₅ * ((x₅ * -0...
                                      .99382) + -0.0047223))) + -3.7731
18          9.360e+00  2.680e-03  y = ((cos(x₃ * -1.5391) + (x₀ * x₀)) * -0.20309) + (((x₅ *...
                                       x₅) * -0.99392) + -3.8094)
20          9.355e+00  2.897e-04  y = ((cos((x₃ + x₃) * 1.2959) + (x₀ * x₀)) * -0.20302) + (...
                                      ((x₅ * -0.99422) * x₅) + -3.7754)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142123_Z0oiRS\hall_of_fame.csv
Best by score: (x0*x0*0.21902357 + x5*x5)*(-1.0104096)
Index 7, score=2.686697
Equation: (((x0 * x0) * 0.21902357) + (x5 * x5)) * -1.0104096

Index 3, score=2.468406
Equation: (x5 * x5) * -1.1541644

Index 4, score=0.325720
Equation: ((x5 * x5) * -1.0048859) + -20.086441

In [167]:
model_1f_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_1_noisy = model_1f_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1f_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.816e+03  1.594e+01  y = -93.862
3           4.654e+03  1.718e-02  y = x₂ + -94.319
4           4.604e+03  1.078e-02  y = p(x₂) + -104.16
5           4.151e+02  2.406e+00  y = x₅ * (x₅ * -1.1573)
7           2.365e+02  2.814e-01  y = (x₅ * (x₅ * -1.0101)) + -19.812
9           2.364e+02  1.641e-04  y = (x₅ * ((x₅ * -1.0093) + -0.033157)) + -19.857
10          2.348e+02  6.827e-03  y = ((x₅ * (x₅ * -1.01)) + sin(x₂)) + -19.809
11          2.338e+02  3.965e-03  y = ((x₄ * 0.19385) + -19.815) + ((x₅ * x₅) * -1.0105)
12          1.362e+02  5.406e-01  y = ((p(x₀) * -1.1022) + ((x₅ * x₅) * -1.071)) + x₀
14          3.397e+01  6.942e-01  y = (((x₅ * -0.36669) * x₅) + (x₀ + (p(x₀) * -0.67127))) *...
                                       2.7362
15          3.126e+01  8.319e-02  y = ((p(x₀) + p(x₀ * -1.0338)) * -0.98169) + (x₅ * (x₅ * -...
                                      1.0043))
17          2.593e+01  9.341e-02  y = ((p(x₀) + p(x₀ * -1.0381)) * -0.97999) + ((x₅ * (x₅ * ...
                                      -1.0044)) + 2.2412)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142126_zwZMLq\hall_of_fame.csv
Best by score: (x0 + x5*(-0.36668792)*x5 + sympy_p(x0)*(-0.67126554))*2.736214
Index 3, score=2.406123
Equation: x5 * (x5 * -1.1573304)

Index 9, score=0.694244
Equation: (((x5 * -0.36668792) * x5) + (x0 + (p(x0) * -0.67126554))) * 2.736214

Index 8, score=0.540603
Equation: ((p(x0) * -1.1022161) + ((x5 * x5) * -1.0710205)) + x0

## 5.11.5 Model 2 with noise std_dev 2 and 5

In [168]:
model_2f_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_2_noisy = model_2f_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2f_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.733e+03  1.594e+01  y = -93.754
3           4.579e+03  1.657e-02  y = x₂ - 94.213
4           3.689e+03  2.160e-01  y = -82.922 - p(x₅)
5           2.001e+02  2.915e+00  y = -20.444 - (x₅ * x₅)
7           2.000e+02  2.677e-04  y = (x₅ * (x₅ * -1.0049)) + -20.087
8           1.980e+02  9.865e-03  y = -20.403 - ((x₅ * x₅) + sin(x₅))
9           1.979e+02  4.846e-04  y = -20.273 - (cos(p(x₁)) + (x₅ * x₅))
10          1.935e+02  2.261e-02  y = -20.273 - (cos(p(exp(x₀))) + (x₅ * x₅))
11          1.348e+01  2.664e+00  y = (x₅ * (x₅ * -1.0104)) + (x₀ * (x₀ * -0.22131))
13          9.500e+00  1.749e-01  y = (((x₅ * -0.99419) * x₅) + ((x₀ * x₀) * -0.20302)) - 3....
                                      7812
15          9.387e+00  6.006e-03  y = ((x₀ * ((x₀ * -0.20303) + 0.036919)) + (x₅ * (x₅ * -0....
                                      99394))) + -3.7668
18          7.908e+00  5.713e-02  y = ((((x₅ * x₅) * -0.9953) + ((x₀ * x₀) * -0.20373)) + co...
                                      s(x₀ * -0.37746)) + -3.4891
20          7.908e+00  2.486e-05  y = ((x₅ * -0.99529) * x₅) + (((x₀ * (x₀ * -0.20376)) + si...
                                      n((x₀ * -0.37778) + 1.552)) + -3.4883)
24          7.836e+00  2.286e-03  y = (((x₅ * x₅) * -0.99513) + ((((x₀ * -0.20373) + 0.03095...
                                      7) * x₀) + (sin((x₀ * -0.3775) + 1.6369) - -6.7837))) + -1...
                                      0.261
29          7.381e+00  1.196e-02  y = ((x₅ * (x₅ * -0.99529)) + (((x₀ * x₀) * -0.20375) + si...
                                      n((-0.37769 * (x₀ + 1.4188)) + -3.4882))) + (sin((x₀ * -0....
                                      37769) + 1.3128) + -3.4882)
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: x0*x0*(-0.20302102) + x5*(-0.9941853)*x5 - 1*3.781187
Index 3, score=2.914507
Equation: -20.444271 - (x5 * x5)

Index 8, score=2.664048
Equation: (x5 * (x5 * -1.0104067)) + (x0 * (x0 * -0.22131279))

Index 2, score=0.216016
Equation: -82.92227 - p(x5)

  - outputs\20250511_142129_Cc10AP\hall_of_fame.csv

In [169]:
model_2f_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_2_noisy = model_2f_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2f_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.816e+03  1.594e+01  y = -93.862
3           4.654e+03  1.718e-02  y = x₂ + -94.324
5           2.369e+02  1.489e+00  y = -20.551 - (x₅ * x₅)
7           2.365e+02  9.610e-04  y = ((x₅ * -1.0101) * x₅) + -19.812
8           2.351e+02  5.914e-03  y = -20.609 - (sin(x₅) + (x₅ * x₅))
9           3.437e+01  1.923e+00  y = (x₀ * (x₀ * -0.23091)) - (x₅ * x₅)
11          3.124e+01  4.780e-02  y = ((x₀ * (x₀ * -0.21069)) + -2.8151) - (x₅ * x₅)
13          3.000e+01  2.020e-02  y = ((x₀ * (x₀ - 0.57805)) * -0.21066) + (-2.7121 - (x₅ * ...
                                      x₅))
15          2.600e+01  7.156e-02  y = ((x₀ * x₀) * ((x₀ * (x₀ * 0.00054847)) + -0.32047)) - ...
                                      (x₅ * x₅)
17          2.529e+01  1.381e-02  y = (x₀ * ((x₀ + -0.37732) * ((x₀ * (x₀ * 0.00053981)) + -...
                                      0.31853))) - (x₅ * x₅)
19          2.518e+01  2.223e-03  y = ((x₀ * (x₀ + -0.37423)) * ((x₀ * (x₀ * 0.00054847)) + ...
                                      -0.32047)) - (x₅ * (x₅ - -0.040552))
20          2.472e+01  1.854e-02  y = ((x₀ * (x₀ + -0.35759)) * (((x₀ * x₀) * 0.00055486) + ...
                                      -0.32154)) - ((x₅ * x₅) - cos(x₄))
22          2.456e+01  3.244e-03  y = ((x₀ * (x₀ + -0.35759)) * (((x₀ * x₀) * 0.00055486) + ...
                                      -0.32154)) - ((x₅ * x₅) - cos(x₄ - -0.4808))
25          2.432e+01  3.217e-03  y = ((x₀ * ((x₀ + -0.39224) * (((x₀ * x₀) * 0.00054305) + ...
                                      -0.31859))) - (x₅ * x₅)) - sin((x₅ * sin(x₄)) * x₅)
27          2.412e+01  4.121e-03  y = ((x₀ * (-0.35457 + x₀)) * ((x₀ * (x₀ * 0.00056335)) + ...
                                      -0.32319)) - (((x₅ * x₅) - (cos(x₄ - exp(x₁)) - 0.55226)) ...
                                      - 0.93604)
29          2.402e+01  2.087e-03  y = (x₀ * (((x₀ * (x₀ * 0.00055821)) + -0.32303) * (x₀ + -...
                                      0.31542))) - (((x₅ * x₅) - (cos(x₄ + (0.19821 - exp(x₁))) ...
                                      - 0.73692)) - 0.9099)
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: x0*x0*(-0.23090877) - x5*x5
Index 5, score=1.922666
Equation: (x0 * (x0 * -0.23090877)) - (x5 * x5)

Index 2, score=1.488882
Equation: -20.550652 - (x5 * x5)

Index 8, score=0.071558
Equation: ((x0 * x0) * ((x0 * (x0 * 0.0005484711)) + -0.32046738)) - (x5 * x5)

  - outputs\20250511_142132_4NwMgG\hall_of_fame.csv

## 5.11.6 Model 3 with noise

In [170]:
model_3f_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_3_noisy = model_3f_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3f_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.733e+03  1.594e+01  y = -93.756
3           4.579e+03  1.657e-02  y = x₂ + -94.213
4           3.689e+03  2.160e-01  y = -82.915 - p(x₅)
5           2.001e+02  2.915e+00  y = -20.445 - (x₅ * x₅)
7           2.000e+02  2.677e-04  y = -20.084 - ((x₅ * x₅) * 1.0049)
8           1.638e+02  1.993e-01  y = x₀ - ((x₅ * x₅) + p(x₀))
10          7.193e+01  4.115e-01  y = x₀ - ((p(x₀) + (x₅ * x₅)) - -9.586)
12          5.409e+01  1.425e-01  y = (x₀ * 1.4625) - ((x₅ * x₅) + (p(x₀) - -9.1841))
14          1.393e+01  6.784e-01  y = (x₀ * 2.6534) - ((x₅ * x₅) + p(x₀ - (x₀ * -0.57278)))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250511_142135_tULtv1\hall_of_fame.csv
Best by score: x0*2.6533859 - (x5*x5 + sympy_p(-(-0.5727765)*x0 + x0))
Index 3, score=2.914507
Equation: -20.444695 - (x5 * x5)

Index 8, score=0.678387
Equation: (x0 * 2.6533859) - ((x5 * x5) + p(x0 - (x0 * -0.5727765)))

Index 6, score=0.411528
Equation: x0 - ((p(x0) + (x5 * x5)) - -9.58604)

In [171]:
model_3f_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_3_noisy = model_3f_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3f_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.816e+03  1.594e+01  y = -93.862
3           4.654e+03  1.718e-02  y = x₂ + -94.319
4           3.757e+03  2.140e-01  y = -83.023 - p(x₅)
5           2.369e+02  2.764e+00  y = -20.551 - (x₅ * x₅)
7           2.365e+02  9.610e-04  y = (-19.615 - (x₅ * x₅)) * 1.0101
8           1.993e+02  1.709e-01  y = (x₀ - p(x₀)) - safe_pow(x₅, 2)
10          1.067e+02  3.123e-01  y = (x₀ - p(x₀)) - (safe_pow(x₅, 2) + 8.5299)
12          5.574e+01  3.247e-01  y = ((x₀ - p(x₀)) - safe_pow(x₅, 2)) - safe_pow(0.7766, x₀...
                                      )
13          2.614e+01  7.572e-01  y = (2.6564 - p(x₀)) - (p(0.43596 - x₀) + safe_pow(x₅, 2))
15          2.613e+01  2.807e-04  y = (1.9357 - p(x₀)) - ((p(0.43596 - x₀) + safe_pow(x₅, 2)...
                                      ) + -0.61321)
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: -(x5**2.0 + sympy_p(0.43596444 - x0)) - sympy_p(x0) + 2.6563637
Index 3, score=2.763811
Equation: -20.550634 - (x5 * x5)

Index 8, score=0.757189
Equation: (2.6563637 - p(x0)) - (p(0.43596444 - x0) + safe_pow(x5, 2.0))

Index 7, score=0.324708
Equation: ((x0 - p(x0)) - safe_pow(x5, 2.0)) - safe_pow(0.7766038, x0)

  - outputs\20250511_142137_DV44CE\hall_of_fame.csv

# 5.12 Output into a DF [5.0]

In [172]:
import pandas as pd

data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5',
    'model_1f', 'model_2f', 'model_3f',
    'model_1f_noisy', 'model_2f_noisy', 'model_3f_noisy',
    'model_1f_wide_range', 'model_2f_wide_range', 'model_3f_wide_range',
    'model_1f_noisy_std_dev_2', 'model_2f_noisy_std_dev_2', 'model_3f_noisy_std_dev_2',
    'model_1f_noisy_std_dev_5', 'model_2f_noisy_std_dev_5', 'model_3f_noisy_std_dev_5',    
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1,best,(x5*x5 + 3.1199038)*(-0.9900283) + cos(x0 + x1...,2.031154
1,model_1,3,x5 * (x5 * -1.1931313),2.031154
2,model_1,4,((x5 * x5) * -0.9815453) + -3.163114,0.560019
3,model_1,10,cos(x1 + (x0 + (x1 + -1.5520582))) + (((x5 * x...,0.548707
4,model_2,best,-x5*x5 - 3.0129306,3.142667
...,...,...,...,...
115,model_2f_noisy_std_dev_5,8,((x0 * x0) * ((x0 * (x0 * 0.0005484711)) + -0....,0.071558
116,model_3f_noisy_std_dev_5,best,-(x5**2.0 + sympy_p(0.43596444 - x0)) - sympy_...,2.763811
117,model_3f_noisy_std_dev_5,3,-20.550634 - (x5 * x5),2.763811
118,model_3f_noisy_std_dev_5,8,(2.6563637 - p(x0)) - (p(0.43596444 - x0) + sa...,0.757189
119,model_3f_noisy_std_dev_5,7,"((x0 - p(x0)) - safe_pow(x5, 2.0)) - safe_pow(...",0.324708

In [173]:
df.to_csv('results5.csv')

In [174]:
data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5',
    'model_1f', 'model_2f', 'model_3f',
    'model_1f_noisy', 'model_2f_noisy', 'model_3f_noisy',
    'model_1f_wide_range', 'model_2f_wide_range', 'model_3f_wide_range',
    'model_1f_noisy_std_dev_2', 'model_2f_noisy_std_dev_2', 'model_3f_noisy_std_dev_2',
    'model_1f_noisy_std_dev_5', 'model_2f_noisy_std_dev_5', 'model_3f_noisy_std_dev_5',    
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

In [175]:
df.to_csv('results5_only_best.csv')