# Zadanie 5: programowanie genetyczne i regresja symboliczna

Adam Tokarz, Serhii Zeliuk

EAIIIB ISI Metody i algorytmy optymalizacji grupa laboratoryjna 2 poniedziałek 18:30

Termin realizacji: 12 maja 2025

Zadanie do oddania przez MS Teams. Do oddania: kod oraz krótkie sprawozdanie w PDF (można na przykład przy użyciu `quarto render notebook.ipynb --to pdf`).

## Na 3.0

Do realizacji:

1. Zmodyfikuj przykład `pysr_demo.ipynb` tak, aby uczył się funkcji $f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$ której dziedziną jest $\mathbb{R}^6$. Uczenie ma się odbywać w oparciu o 200 wylosowanych z dziedziny próbek (między -5 a 5).
2. Zanotuj wzory trzech rozwiązań o najwyższej wartości `score` oraz rozwiązanie `best` dla następujących zestawów ustawień:
   1. `binary_operators=["+", "*"], unary_operators=["cos", "exp", "sin"], maxsize=20`,
   2. `binary_operators=["+", "*", "-", "^"], unary_operators=["cos", "exp", "sin", "log"], maxsize=30`, (dodaj ograniczenie dla argumentów operatora "^").
   3. `binary_operators=["+", "*", "-", "^"], unary_operators=["exp", "sin"], maxsize=15`.
3. Powtórz eksperymenty z zadania na 3.0 po dodaniu szumu do próbek z funkcji $f$ (rozkład normalny o średniej 0 i odchyleniu standardowym 0.5)

## Na 4.0

Do realizacji:

1. Punkty z zadania na 3.0.
2. Dodaj do porównania dopasowanie oparte o próbki losowane w szerszym zakresie (między -15 a 15) oraz wyższy poziom szumu (odchylenie standardowe równe 2 oraz 5).

## Na 5.0

Do realizacji:

1. Punkty z zadania na 4.0.
2. Zamień funkcję $f$ na $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$ gdzie $p(i)$ oznacza $i$-tą liczbę pierwszą. Uwzględnij `p` jako dodatkowy operator unarny analogicznie do przykładu "Julia packages and types" z notatnika `pysr_demo.ipynb`. Powtórz eksperymenty opisane w zadaniach na 3.0 i 4.0.

In [169]:
import pysr
import sympy
import numpy as np
from matplotlib import pyplot as plt
from pysr import PySRRegressor
from sklearn.model_selection import train_test_split

# 5.1 Function f [3.0]

$$f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$$

- X (random values  $\mathbb{R}^6$ [-5, 5])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev = 0.5)

In [170]:
from numpy import sin, cos, exp, log, sqrt
# Dataset

np.random.seed(0)
X = np.random.uniform(-5, 5, size=(200, 6))
# y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 2
y = 2.2*sin(X[:, 0] + 2*X[:, 1]) - X[:, 5] ** 2 - 3
# Add the y samples with random noise
noise = np.random.normal(loc=0.0, scale=0.5, size=y.shape)
y_noisy = y + noise

In [171]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

# 5.2 Experiments [3.0]

## 5.2.1 Model 1

In [172]:
model_1 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.158
3           5.546e+01  1.240e-03  y = x₂ + -11.311
4           5.152e+01  7.370e-02  y = cos(x₅) + -10.987
5           6.759e+00  2.031e+00  y = (x₅ * x₅) * -1.1931
7           2.205e+00  5.600e-01  y = ((x₅ * x₅) * -0.98153) + -3.1632
9           2.197e+00  1.884e-03  y = (x₅ * ((x₅ + 0.033223) * -0.9792)) + -3.1778
11          2.173e+00  5.516e-03  y = (((x₅ * x₅) + 3.2189) + (x₀ * -0.06038)) * -0.98035
12          2.106e+00  3.128e-02  y = (sin(x₀) + ((x₅ * (x₅ * 2.2522)) + 7.367)) * -0.43395
14          6.561e-01  5.831e-01  y = (((x₅ * -0.98993) * x₅) + sin(x₀ + (x₁ + x₁))) + -3.08...
                                      9
16          6.557e-01  2.889e-04  y = (sin((x₀ + x₁) + (x₁ + 0.018688)) + (x₅ * (x₅ * -0.990...
                                      02))) + -3.0888
18          6.550e-01  5.164e-04  y = (x₅ * (x₅ * -0.98992)) + (sin((x₁ + (x₂ * -0.011121)) ...
                                      + (x₀ + x₁)) + -3.0859)
20          6.522e-01  2.200e-03  y = (((x₅ * -0.98998) * x₅) + sin((x₁ + x₀) + (x₁ + ((x₁ *...
                                       x₂) * 0.0074334)))) + -3.0932
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_152231_euo030\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                          -11.15813
	1         0.001240                                    x2 + -11.310952
	2         0.073704                                cos(x5) + -10.98749
	3         2.031154                             (x5 * x5) * -1.1931036
	4         0.560019               ((x5 * x5) * -0.981529) + -3.1631775
	5         0.001884  (x5 * ((x5 + 0.033223346) * -0.9791992)) + -3....
	6         0.005516  (((x5 * x5) + 3.2189353) + (x0 * -0.0603795)) ...
	7         0.031284  (sin(x0) + ((x5 * (x5 * 2.252192)) + 7.3669887...
	8   >>>>  0.583093  (((x5 * -0.9899335) * x5) + sin(x0 + (x1 + x1)...
	9         0.000289  (sin((x0 + x1) + (x1 + 0.018687906)) + (x5 * (...
	10        0.000516  (x5 * (x5 * -0.9899174)) + (sin((x1 + (x2 * -0...
	11        0.002201  (((x5 * -0.98998225) * x5) + sin((x1 + x0) + (...

	         loss  complexity
	0   55.599790           1
	1   55.462025           3
	2   51.521240           4
	3    6.758767           5
	4    2.205166           7
	5    2.196871           9
	6    2.172767          11
	7    2.105847          12
	8    0.656082          14
	9    0.655703          16
	10   0.655026          18
	11   0.652150          20
]

### Model 1 best + top3 according to score

In [173]:
best_equation_1 = model_1.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x5*(-0.9899335)*x5 + sin(x0 + x1 + x1) - 3.0889764
Index 3, score=2.031154
Equation: (x5 * x5) * -1.1931036

Index 8, score=0.583093
Equation: (((x5 * -0.9899335) * x5) + sin(x0 + (x1 + x1))) + -3.0889764

Index 4, score=0.560019
Equation: ((x5 * x5) * -0.981529) + -3.1631775

## 5.2.2 Model 2

Added constraint to operator "^" - safe_pow

In [174]:
%%julia
function safe_pow(x::T, y::T) where T
    if(x < 0 && floor(y) != y)
        return T(NaN)
    else
        return T(x^y)
    end
end

safe_pow (generic function with 2 methods)

In [175]:
def safe_pow(x, y):
    if x < 0 and np.floor(y) != y:
        return np.nan
    return np.power(x, y)

model_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.158
3           5.537e+01  2.051e-03  y = -11.021 - x₅
4           5.152e+01  7.208e-02  y = cos(x₅) - 10.987
5           2.224e+00  3.143e+00  y = -3.0128 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = ((x₅ * -0.98155) * x₅) - 3.1631
9           2.194e+00  2.514e-03  y = -2.9964 - ((x₅ * x₅) - (x₀ * 0.056847))
10          2.134e+00  2.777e-02  y = (-3.0123 - (x₅ * x₅)) - (sin(x₀) * 0.41052)
11          2.048e+00  4.110e-02  y = (-3.0123 - (x₅ * x₅)) - (cos(x₁) * sin(x₁))
13          2.047e+00  3.141e-04  y = -3.0441 - ((x₅ * x₅) - (cos(x₁) * cos(x₁ + -4.703)))
15          1.732e+00  8.355e-02  y = -2.9659 - ((x₅ * x₅) - sin((x₀ + (cos(x₁) * -2.5836)) ...
                                      * -1.1016))
17          1.434e+00  9.439e-02  y = (-2.9873 - (x₅ * x₅)) - (sin((x₁ + x₀) * -2.0004) * co...
                                      s(0.083588 - x₀))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_152233_HtV0On\hall_of_fame.csv

[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.158203
	1         0.002051                                    -11.020777 - x5
	2         0.072084                                cos(x5) - 10.987481
	3         3.142667                             -3.0127745 - (x5 * x5)
	4         0.004262                ((x5 * -0.981549) * x5) - 3.1631365
	5         0.002514      -2.9963903 - ((x5 * x5) - (x0 * 0.056846745))
	6         0.027774    (-3.012335 - (x5 * x5)) - (sin(x0) * 0.4105221)
	7         0.041096      (-3.012335 - (x5 * x5)) - (cos(x1) * sin(x1))
	8         0.000314  -3.0441155 - ((x5 * x5) - (cos(x1) * cos(x1 + ...
	9         0.083551  -2.9659462 - ((x5 * x5) - sin((x0 + (cos(x1) *...
	10  >>>>  0.094392  (-2.9872622 - (x5 * x5)) - (sin((x1 + x0) * -2...

	         loss  complexity
	0   55.599790           1
	1   55.372204           3
	2   51.521240           4
	3    2.224043           5
	4    2.205166           7
	5    2.194107           9
	6    2.134007          10
	7    2.048086          11
	8    2.046799          13
	9    1.731823          15
	10   1.433890          17
]

In [176]:
best_equation_2 = model_2.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - sin((x0 + x1)*(-2.000435))*cos(0.08358824 - x0) - 2.9872622
Index 3, score=3.142667
Equation: -3.0127745 - (x5 * x5)

Index 10, score=0.094392
Equation: (-2.9872622 - (x5 * x5)) - (sin((x1 + x0) * -2.000435) * cos(0.08358824 - x0))

Index 9, score=0.083551
Equation: -2.9659462 - ((x5 * x5) - sin((x0 + (cos(x1) * -2.5835772)) * -1.1015854))

## 5.2.3 Model 3

In [177]:
model_3 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.158
3           5.537e+01  2.051e-03  y = -11.021 - x₅
4           5.462e+01  1.364e-02  y = -11.157 - sin(x₀)
5           2.224e+00  3.201e+00  y = -3.0128 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = ((x₅ * x₅) * -0.98154) + -3.1631
9           2.197e+00  1.884e-03  y = (x₅ * ((x₅ + 0.033274) * -0.97923)) + -3.1775
11          2.173e+00  5.516e-03  y = (((x₅ * x₅) * -0.98035) + -3.1557) + (x₀ * 0.059192)
12          2.106e+00  3.128e-02  y = ((x₅ * (x₅ * -0.97732)) + -3.1973) + (sin(x₀) * -0.433...
                                      36)
13          2.105e+00  6.333e-04  y = ((x₅ * (x₅ * -0.97719)) + -3.1972) + (sin(sin(x₀)) * -...
                                      0.49714)
14          2.023e+00  3.933e-02  y = ((x₅ * (x₅ * -0.98203)) + (sin(x₁ + x₁) * -0.60402)) +...
                                       -3.2017
15          2.023e+00  3.349e-04  y = (sin(sin(x₁ + x₁) * -0.64107) + -3.202) + (x₅ * (x₅ * ...
                                      -0.98203))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.158492
	1         0.002051                                    -11.020796 - x5
	2         0.013642                               -11.157393 - sin(x0)
	3   >>>>  3.201109                             -3.0128005 - (x5 * x5)
	4         0.004262              ((x5 * x5) * -0.98154336) + -3.163127
	5         0.001884  (x5 * ((x5 + 0.033273842) * -0.97922534)) + -3...
	6         0.005516  (((x5 * x5) * -0.9803535) + -3.1556895) + (x0 ...
	7         0.031284  ((x5 * (x5 * -0.9773174)) + -3.1972888) + (sin...
	8         0.000633  ((x5 * (x5 * -0.97718763)) + -3.1971612) + (si...
	9         0.039329  ((x5 * (x5 * -0.9820347)) + (sin(x1 + x1) * -0...
	10        0.000335  (sin(sin(x1 + x1) * -0.6410692) + -3.202018) +...

	         loss  complexity
	0   55.599800           1
	1   55.372204           3
	2   54.621952           4
	3    2.224043           5
	4    2.205166           7
	5    2.196871           9
	6    2.172767          11
	7    2.105847          12
	8    2.104514          13
	9    2.023352          14
	10   2.022674          15
]

  - outputs\20250510_152238_LotbFM\hall_of_fame.csv

In [178]:
best_equation_3 = model_3.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 3.0128005
Index 3, score=3.201109
Equation: -3.0128005 - (x5 * x5)

Index 9, score=0.039329
Equation: ((x5 * (x5 * -0.9820347)) + (sin(x1 + x1) * -0.60402435)) + -3.2016938

Index 7, score=0.031284
Equation: ((x5 * (x5 * -0.9773174)) + -3.1972888) + (sin(x0) * -0.43336007)

## 5.2.4 Model 1 with noise

In [179]:
model_1_noisy.fit(X, y_noisy)
best_equation_1_noisy = model_1_noisy.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1_noisy.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.093
3           5.560e+01  5.027e-04  y = x₂ + -11.246
4           5.159e+01  7.493e-02  y = cos(x₅) + -10.922
5           6.855e+00  2.018e+00  y = (x₅ * -1.188) * x₅
7           2.449e+00  5.148e-01  y = (x₅ * (x₅ * -0.97982)) + -3.1117
9           2.434e+00  2.937e-03  y = (x₅ * ((x₅ * -0.97674) + -0.04277)) + -3.1309
11          2.363e+00  1.485e-02  y = ((((x₄ * -0.037462) + x₅) * -0.97839) * x₅) + -3.1303
12          2.346e+00  7.329e-03  y = ((x₅ * (x₅ * -0.97556)) + (sin(x₀) * -0.44094)) + -3.1...
                                      459
13          2.345e+00  1.453e-04  y = ((((x₄ + -1.228) * 0.037724) + (x₅ * -0.97452)) * x₅) ...
                                      + -3.1586
14          2.264e+00  3.514e-02  y = (x₅ * (x₅ * -0.98038)) + ((sin(x₁ * 2.0074) * -0.60911...
                                      ) + -3.1492)
18          2.261e+00  4.099e-04  y = (((x₅ * x₅) * -0.98057) + ((sin(x₁ * 2.0111) * -0.6058...
                                      8) + -3.1475)) + (x₃ * -0.0035361)
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: x5*x5*(-0.9798246) - 3.1116507
Index 3, score=2.018258
Equation: (x5 * -1.1879799) * x5

Index 4, score=0.514755
Equation: (x5 * (x5 * -0.9798246)) + -3.1116507

Index 2, score=0.074934
Equation: cos(x5) + -10.922028

  - outputs\20250510_152242_0pIYpG\hall_of_fame.csv

## 5.2.5 Model 2 with noise

In [180]:
model_2_noisy.fit(X, y_noisy)
best_equation_2_noisy = model_2_noisy.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2_noisy.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.093
3           5.528e+01  3.374e-03  y = -10.955 - x₅
4           5.159e+01  6.919e-02  y = cos(x₅) + -10.922
5           2.471e+00  3.039e+00  y = -2.9471 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = ((x₅ * x₅) * -0.97982) + -3.1116
9           2.435e+00  2.784e-03  y = (-1.9068 - (x₅ * x₅)) - safe_pow(0.93532, x₀)
11          2.339e+00  2.001e-02  y = cos(x₁ + cos(x₁)) + (-2.7763 - (x₅ * x₅))
12          8.930e-01  9.630e-01  y = (-2.9415 - (x₅ * x₅)) + sin(x₁ + (x₀ + x₁))
14          8.917e-01  7.319e-04  y = sin((x₁ + x₁) + (x₀ - -0.034488)) + (-2.9426 - (x₅ * x...
                                      ₅))
19          2.424e-01  2.605e-01  y = ((-2.8443 - (x₅ * x₅)) + sin(x₁ + (x₁ + x₀))) + sin((x...
                                      ₁ + x₀) + x₁)
23          2.334e-01  9.404e-03  y = ((-2.9367 - (x₅ * x₅)) + sin(x₁ + (x₁ + (x₀ - -0.01583...
                                      3)))) + sin(x₁ + ((x₀ - -0.01592) + x₁))
27          2.334e-01  -0.000e+00  y = sin((x₀ - -0.015895) + (x₁ + x₁)) + (((sin((x₁ + (x₀ ...
                                       - -0.015857)) + x₁) + -3.566) - ((x₅ * x₅) - 0.27483)) - ...
                                       -0.3545)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_152245_Lnrckm\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

Best by score: -x5*x5 + sin(x0 + x1 + x1) + sin(x0 + x1 + x1) - 2.844277
Index 3, score=3.038596
Equation: -2.9470925 - (x5 * x5)

Index 7, score=0.963023
Equation: (-2.9414787 - (x5 * x5)) + sin(x1 + (x0 + x1))

Index 9, score=0.260538
Equation: ((-2.844277 - (x5 * x5)) + sin(x1 + (x1 + x0))) + sin((x1 + x0) + x1)

## 5.2.6 Model 3 with noise

In [181]:
model_3_noisy.fit(X, y_noisy)
best_equation_3_noisy = model_3_noisy.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3_noisy.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.092
3           5.528e+01  3.374e-03  y = -10.955 - x₅
4           5.467e+01  1.109e-02  y = -11.092 - sin(x₀)
5           2.471e+00  3.097e+00  y = -2.9473 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = -3.1117 - (x₅ * (x₅ * 0.97982))
9           2.434e+00  2.937e-03  y = -3.1309 - (x₅ * ((x₅ * 0.97674) + 0.042773))
10          2.360e+00  3.105e-02  y = (sin(x₁ * -2.0249) + -3.0127) - (x₅ * x₅)
11          2.316e+00  1.853e-02  y = (-3.1868 - (x₅ * x₅)) + sin(exp(x₁ + 0.92781))
12          8.930e-01  9.532e-01  y = (-2.9413 - (x₅ * x₅)) + sin((x₀ + x₁) + x₁)
14          8.929e-01  8.512e-05  y = sin(x₁ + ((x₀ * 0.99615) + x₁)) + (-2.9427 - (x₅ * x₅)...
                                      )
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

Best by score: -x5*x5 + sin(x0 + x1 + x1) - 2.9413362
Index 3, score=3.096697
Equation: -2.9472663 - (x5 * x5)

Index 8, score=0.953158
Equation: (-2.9413362 - (x5 * x5)) + sin((x0 + x1) + x1)

Index 6, score=0.031051
Equation: (sin(x1 * -2.024923) + -3.0127091) - (x5 * x5)

  - outputs\20250510_152247_qAWYOp\hall_of_fame.csv

# 5.3 Output into a DF [3.0]

In [182]:
import pandas as pd

data = []

for model_name in ['model_1', 'model_2', 'model_3','model_1_noisy', 'model_2_noisy', 'model_3_noisy']:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1,best,x5*(-0.9899335)*x5 + sin(x0 + x1 + x1) - 3.088...,2.031154
1,model_1,3,(x5 * x5) * -1.1931036,2.031154
2,model_1,8,(((x5 * -0.9899335) * x5) + sin(x0 + (x1 + x1)...,0.583093
3,model_1,4,((x5 * x5) * -0.981529) + -3.1631775,0.560019
4,model_2,best,-x5*x5 - sin((x0 + x1)*(-2.000435))*cos(0.0835...,3.142667
5,model_2,3,-3.0127745 - (x5 * x5),3.142667
6,model_2,10,(-2.9872622 - (x5 * x5)) - (sin((x1 + x0) * -2...,0.094392
7,model_2,9,-2.9659462 - ((x5 * x5) - sin((x0 + (cos(x1) *...,0.083551
8,model_3,best,-x5*x5 - 3.0128005,3.201109
9,model_3,3,-3.0128005 - (x5 * x5),3.201109
10,model_3,9,((x5 * (x5 * -0.9820347)) + (sin(x1 + x1) * -0...,0.039329
11,model_3,7,((x5 * (x5 * -0.9773174)) + -3.1972888) + (sin...,0.031284
12,model_1_noisy,best,x5*x5*(-0.9798246) - 3.1116507,2.018258
13,model_1_noisy,3,(x5 * -1.1879799) * x5,2.018258
14,model_1_noisy,4,(x5 * (x5 * -0.9798246)) + -3.1116507,0.514755
15,model_1_noisy,2,cos(x5) + -10.922028,0.074934
16,model_2_noisy,best,-x5*x5 + sin(x0 + x1 + x1) + sin(x0 + x1 + x1)...,3.038596
17,model_2_noisy,3,-2.9470925 - (x5 * x5),3.038596
18,model_2_noisy,7,(-2.9414787 - (x5 * x5)) + sin(x1 + (x0 + x1)),0.963023
19,model_2_noisy,9,((-2.844277 - (x5 * x5)) + sin(x1 + (x1 + x0))...,0.260538
20,model_3_noisy,best,-x5*x5 + sin(x0 + x1 + x1) - 2.9413362,3.096697
21,model_3_noisy,3,-2.9472663 - (x5 * x5),3.096697
22,model_3_noisy,8,(-2.9413362 - (x5 * x5)) + sin((x0 + x1) + x1),0.953158
23,model_3_noisy,6,(sin(x1 * -2.024923) + -3.0127091) - (x5 * x5),0.031051

In [183]:
df.to_csv('results3.csv')

# 5.4 Function f [4.0]

$$f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$$

- X (random values  $\mathbb{R}^6$ [-15, 15])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev1 = 2, std_dev2 = 5)

In [184]:
from numpy import sin, cos, exp, log, sqrt
# Dataset

np.random.seed(0)
X = np.random.uniform(-15, 15, size=(200, 6))
# y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 2
y = 2.2*sin(X[:, 0] + 2*X[:, 1]) - X[:, 5] ** 2 - 3
# Add the y samples with random noise
noise1 = np.random.normal(loc=0.0, scale=2, size=y.shape)
y_noisy1 = y + noise1
noise2 = np.random.normal(loc=0.0, scale=5, size=y.shape)
y_noisy2 = y + noise2

In [185]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

# 5.5 Experiments [4.0]

## 5.5.1 Model 1

In [186]:
model_1_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.289
3           4.338e+03  1.665e-02  y = x₂ + -76.745
5           6.228e+00  3.273e+00  y = (x₅ * x₅) * -1.0218
7           2.054e+00  5.546e-01  y = ((x₅ * -0.99929) * x₅) + -3.0285
9           2.022e+00  7.920e-03  y = (x₅ * ((x₅ * -0.99981) + 0.02139)) + -2.9996
12          1.997e+00  4.119e-03  y = ((((cos(x₃) * -0.040072) + x₅) * x₅) + 3.0116) * -0.99...
                                      963
13          1.986e+00  5.572e-03  y = ((2.2818 + cos(cos(x₅ * 1.9422))) + (x₅ * x₅)) * -0.99...
                                      928
14          1.972e+00  6.830e-03  y = (((x₅ * x₅) + cos(cos(exp(x₅ * -1.4135)))) * -0.99944)...
                                       + -2.367
15          1.886e+00  4.495e-02  y = (((x₅ * x₅) + 2.164) + cos(cos(x₁ + exp(cos(x₀))))) * ...
                                      -0.99938
17          1.878e+00  2.066e-03  y = ((((x₅ * x₅) + 2.164) + cos(cos(x₁ + exp(cos(x₀))))) +...
                                       0.088356) * -0.99938
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	   pick     score                                           equation  \
	0        0.000000                                           -76.2889
	1        0.016651                                     x2 + -76.74525
	2        3.273026                             (x5 * x5) * -1.0218042
	3  >>>>  0.554636               ((x5 * -0.9992922) * x5) + -3.028511
	4        0.007920  (x5 * ((x5 * -0.99980634) + 0.0213904)) + -2.9...
	5        0.004119  ((((cos(x3) * -0.040071655) + x5) * x5) + 3.01...
	6        0.005572  ((2.2817693 + cos(cos(x5 * 1.9422213))) + (x5 ...
	7        0.006830  (((x5 * x5) + cos(cos(exp(x5 * -1.413547)))) *...
	8        0.044949  (((x5 * x5) + 2.1640432) + cos(cos(x1 + exp(co...
	9        0.002066  ((((x5 * x5) + 2.1640432) + cos(cos(x1 + exp(c...

	          loss  complexity
	0  4484.837400           1
	1  4337.941400           3
	2     6.228301           5
	3     2.054086           7
	4     2.021807           9
	5     1.996980          12
	6     1.985883          13
	7     1.972366          14
	8     1.885673          15
	9     1.877900          17
]

  - outputs\20250510_152249_15ICir\hall_of_fame.csv

### Model 1 best + top3 according to score

In [187]:
best_equation_1 = model_1_wide_range.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x5*(-0.9992922)*x5 - 3.028511
Index 2, score=3.273026
Equation: (x5 * x5) * -1.0218042

Index 3, score=0.554636
Equation: ((x5 * -0.9992922) * x5) + -3.028511

Index 8, score=0.044949
Equation: (((x5 * x5) + 2.1640432) + cos(cos(x1 + exp(cos(x0))))) * -0.9993811

## 5.5.2 Model 2

In [188]:

model_2_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.297
3           4.338e+03  1.665e-02  y = x₂ + -76.745
5           2.056e+00  3.827e+00  y = -2.9764 - (x₅ * x₅)
7           2.022e+00  8.427e-03  y = ((0.021684 - x₅) * x₅) - 2.9855
9           2.022e+00  4.009e-05  y = (x₅ * ((0.021393 - x₅) * 0.99981)) - 2.9997
11          2.005e+00  4.132e-03  y = ((x₅ - (x₁ * -0.0017115)) * (0.019324 - x₅)) + -2.9882
12          1.985e+00  1.019e-02  y = (x₅ * ((0.021036 - x₅) - (sin(x₄) * 0.030947))) + -3.0...
                                      062
13          1.976e+00  4.639e-03  y = ((x₅ * (0.022089 - x₅)) + -2.9586) - (sin(exp(x₅)) * 0...
                                      .44242)
14          6.113e-01  1.173e+00  y = (-2.9859 - (x₅ * x₅)) - sin((x₀ - (-21.969 - x₁)) + x₁...
                                      )
18          6.016e-01  3.993e-03  y = -2.9921 - ((x₅ * (x₅ - 0.011812)) - sin(x₀ - ((x₀ - x₀...
                                      ) - (x₁ + x₁))))
20          6.012e-01  2.754e-04  y = -2.9911 - ((x₅ * (x₅ - 0.011715)) - sin((x₀ - 0.017609...
                                      ) - ((x₀ - x₀) - (x₁ + x₁))))
27          6.012e-01  -0.000e+00  y = -1.7714 - (((x₀ - x₀) + 2.2198) + (((x₅ - 0.011711) *...
                                        x₅) - (cos(x₀ - x₀) - sin((0.017526 - x₀) - (x₁ + x₁))))...
                                       )
28          6.002e-01  1.757e-03  y = -2.9191 - (((((x₅ - 0.011618) * x₅) - sin((x₀ - 0.0161...
                                      7) - (((x₀ + 0.42971) * -0.0034367) - (x₁ + x₁)))) + x₀) -...
                                       (x₀ - 0.07072))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick         score                                           equation  \
	0         0.000000e+00                                         -76.297134
	1         1.665117e-02                                    x2 + -76.745255
	2         3.827115e+00                             -2.9764159 - (x5 * x5)
	3         8.427353e-03               ((0.02168417 - x5) * x5) - 2.9855106
	4         4.013578e-05  (x5 * ((0.02139293 - x5) * 0.9998078)) - 2.999...
	5         4.132585e-03  ((x5 - (x1 * -0.0017115202)) * (0.0193236 - x5...
	6         1.018981e-02  (x5 * ((0.021035833 - x5) - (sin(x4) * 0.03094...
	7         4.639543e-03  ((x5 * (0.022089256 - x5)) + -2.9585779) - (si...
	8   >>>>  1.173122e+00  (-2.985921 - (x5 * x5)) - sin((x0 - (-21.96852...
	9         3.993391e-03  -2.9920983 - ((x5 * (x5 - 0.011811689)) - sin(...
	10        2.754351e-04  -2.9910588 - ((x5 * (x5 - 0.011714951)) - sin(...
	11        2.376016e-08  -1.771405 - (((x0 - x0) + 2.2197688) + (((x5 -...
	12        1.757296e-03  -2.9190538 - (((((x5 - 0.011618117) * x5) - si...

	           loss  complexity
	0   4484.837400           1
	1   4337.941400           3
	2      2.056337           5
	3      2.021968           7
	4      2.021806           9
	5      2.005164          11
	6      1.984836          12
	7      1.975648          13
	8      0.611264          14
	9      0.601578          18
	10     0.601247          20
	11     0.601246          27
	12     0.600191          28
]

  - outputs\20250510_152251_1iH9Yl\hall_of_fame.csv

In [189]:
best_equation_2 = model_2_wide_range.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - sin(x0 + x1 - (-x1 - 21.968521)) - 2.985921
Index 2, score=3.827115
Equation: -2.9764159 - (x5 * x5)

Index 8, score=1.173122
Equation: (-2.985921 - (x5 * x5)) - sin((x0 - (-21.968521 - x1)) + x1)

Index 1, score=0.016651
Equation: x2 + -76.745255

## 5.5.3 Model 3

In [190]:
model_3_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={ "safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.288
3           4.338e+03  1.665e-02  y = x₂ + -76.745
5           2.056e+00  3.827e+00  y = -2.9764 - (x₅ * x₅)
7           2.022e+00  8.427e-03  y = -2.9856 - (x₅ * (x₅ + -0.021677))
9           2.022e+00  4.003e-05  y = -2.9996 - ((x₅ * (x₅ + -0.021396)) * 0.99981)
10          2.014e+00  3.987e-03  y = -3.0083 - (x₅ * (x₅ + (sin(x₃) * -0.03415)))
11          2.005e+00  4.276e-03  y = -2.9883 - (((x₁ * 0.0017111) + (x₅ + -0.019343)) * x₅)
12          1.971e+00  1.725e-02  y = ((sin(x₄ * x₄) * -0.40875) + -2.9384) - (x₅ * x₅)
13          1.941e+00  1.503e-02  y = (sin(exp(x₁) * (x₅ + 7.0652)) + -2.9496) - (x₅ * x₅)
14          1.939e+00  1.458e-03  y = sin(x₅ * ((x₅ + -0.32063) * -0.25501)) + (-2.9318 - (x...
                                      ₅ * x₅))
15          1.908e+00  1.580e-02  y = (-2.9372 - (x₅ * x₅)) + sin(sin((x₅ * (x₅ + -0.31914))...
                                       * -0.25513))
───────────────────────────────────────────────────────────────────────────────────────────────────

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -76.288445
	1         0.016651                                     x2 + -76.74523
	2   >>>>  3.827115                             -2.9763682 - (x5 * x5)
	3         0.008427             -2.9855747 - (x5 * (x5 + -0.02167654))
	4         0.000040  -2.9996483 - ((x5 * (x5 + -0.02139574)) * 0.99...
	5         0.003988  -3.0082898 - (x5 * (x5 + (sin(x3) * -0.0341498...
	6         0.004276  -2.9882543 - (((x1 * 0.0017111487) + (x5 + -0....
	7         0.017249  ((sin(x4 * x4) * -0.40875223) + -2.938439) - (...
	8         0.015026  (sin(exp(x1) * (x5 + 7.0651875)) + -2.9496315)...
	9         0.001458  sin(x5 * ((x5 + -0.32062864) * -0.2550119)) + ...
	10        0.015799  (-2.9372296 - (x5 * x5)) + sin(sin((x5 * (x5 +...

	           loss  complexity
	0   4484.837400           1
	1   4337.941400           3
	2      2.056337           5
	3      2.021969           7
	4      2.021807           9
	5      2.013761          10
	6      2.005168          11
	7      1.970878          12
	8      1.941484          13
	9      1.938656          14
	10     1.908268          15
]

  - outputs\20250510_152254_S1bMDw\hall_of_fame.csv

In [191]:
best_equation_3 = model_3_wide_range.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 2.9763682
Index 2, score=3.827115
Equation: -2.9763682 - (x5 * x5)

Index 7, score=0.017249
Equation: ((sin(x4 * x4) * -0.40875223) + -2.938439) - (x5 * x5)

Index 1, score=0.016651
Equation: x2 + -76.74523

## 5.5.4 Model 1 with noise std_dev 2 and 5

In [192]:
model_1_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_1_noisy = model_1_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.022
3           4.336e+03  1.655e-02  y = x₂ + -76.481
5           9.261e+00  3.074e+00  y = x₅ * (x₅ * -1.0195)
7           5.635e+00  2.484e-01  y = (x₅ * (x₅ * -0.99853)) + -2.8222
9           5.631e+00  3.749e-04  y = (((x₅ + -0.0077544) * -0.99871) * x₅) + -2.8126
11          5.543e+00  7.899e-03  y = (((x₅ * x₅) + sin(exp(x₄))) * -0.99938) + -2.665
12          5.147e+00  7.395e-02  y = sin(x₀ * 1.4498) + (((x₅ * -0.9984) * x₅) + -2.8636)
16          5.125e+00  1.116e-03  y = (sin(((x₅ * x₅) * 0.58638) + 2.064) + (x₅ * (x₅ * -0.9...
                                      9754))) + -2.8809
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_152256_lSfe9F\hall_of_fame.csv
Best by score: x5*x5*(-0.99853265) - 2.822184
Index 2, score=3.074411
Equation: x5 * (x5 * -1.0195066)

Index 3, score=0.248400
Equation: (x5 * (x5 * -0.99853265)) + -2.822184

Index 6, score=0.073948
Equation: sin(x0 * 1.4497756) + (((x5 * -0.99840003) * x5) + -2.8635812)

In [193]:
model_1_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_1_noisy = model_1_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.134
3           4.394e+03  1.726e-02  y = x₂ + -76.589
5           2.874e+01  2.515e+00  y = x₅ * (x₅ * -1.0227)
7           2.578e+01  5.427e-02  y = (x₅ * (x₅ * -1.0037)) + -2.5487
9           2.573e+01  9.794e-04  y = ((x₅ + 0.026667) * (x₅ * -1.0031)) + -2.5848
10          2.532e+01  1.615e-02  y = ((x₅ * (x₅ * -1.0035)) + -2.616) + cos(x₄)
11          2.495e+01  1.475e-02  y = (((x₅ * x₅) * -1.003) + -2.51) + (x₀ * 0.10008)
12          2.467e+01  1.131e-02  y = ((x₅ * (x₅ * -1.004)) + sin(x₄ * x₅)) + -2.5135
14          2.424e+01  8.858e-03  y = (((x₅ * -1.0037) * x₅) + sin((x₅ * 6.5853) + -2.2184))...
                                       + -2.5493
17          2.382e+01  5.852e-03  y = (((x₅ * x₅) * -1.0025) + sin(x₅ * 11.712)) + (sin(x₅ *...
                                       x₄) + -2.629)
19          2.363e+01  3.904e-03  y = (sin(x₅ * 11.691) + (x₅ * (x₅ * -1.0028))) + ((sin(x₅ ...
                                      * x₄) + -1.5811) * 1.6429)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_152259_olByp0\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

Best by score: x5*x5*(-1.0226563)
Index 2, score=2.514830
Equation: x5 * (x5 * -1.0226563)

Index 3, score=0.054270
Equation: (x5 * (x5 * -1.0037103)) + -2.5486856

Index 1, score=0.017257
Equation: x2 + -76.58875

## 5.5.5 Model 2 with noise std_dev 2 and 5

In [194]:
model_2_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_2_noisy = model_2_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.027
3           4.336e+03  1.655e-02  y = x₂ + -76.487
5           5.645e+00  3.322e+00  y = -2.7147 - (x₅ * x₅)
7           5.635e+00  8.622e-04  y = (-2.8268 - (x₅ * x₅)) * 0.99853
9           5.581e+00  4.837e-03  y = cos(cos(x₃)) - ((x₅ * x₅) + 3.486)
10          5.544e+00  6.563e-03  y = (cos(x₁ * -0.10063) - (x₅ * x₅)) + -3.3438
11          5.506e+00  6.906e-03  y = cos(-0.50756 - sin(x₅)) - ((x₅ * x₅) + 3.3976)
12          5.376e+00  2.390e-02  y = cos(x₁ * (x₂ + -0.7969)) - ((x₅ * x₅) + 2.7027)
14          5.263e+00  1.060e-02  y = cos((x₄ - 6.5764) * (-4.4869 - x₂)) - ((x₅ * x₅) + 2.6...
                                      365)
19          5.187e+00  2.915e-03  y = cos((((cos(exp(x₂)) * x₀) + cos(x₅)) * 0.63748) + 1.60...
                                      28) - ((x₅ * x₅) + 2.779)
20          5.182e+00  9.961e-04  y = cos(exp(0.54994) + (((cos(exp(x₂)) * x₀) + cos(x₅)) * ...
                                      0.63748)) - ((x₅ * x₅) + 2.779)
21          5.145e+00  7.131e-03  y = cos((((cos(exp(x₂)) * x₀) + cos(-0.42064 - x₅)) * 0.63...
                                      748) + 1.6028) - ((x₅ * x₅) + 2.779)
22          5.142e+00  6.909e-04  y = cos((((cos(exp(x₂)) * x₀) + cos(sin(-0.90194) - x₅)) *...
                                       0.63748) + 1.6028) - ((x₅ * x₅) + 2.779)
23          5.095e+00  9.051e-03  y = (cos(((cos(exp(-0.36267)) - x₀) + ((x₀ + cos(x₂)) * -0...
                                      .43426)) + 0.91506) - ((x₅ * x₅) + 0.39889)) - 2.3215
24          5.094e+00  1.944e-04  y = cos((((cos((x₅ * x₅) + 6.8733) + x₀) + cos(x₅ - -1.075...
                                      9)) * 0.67657) + 1.3777) - ((x₅ * x₅) + 2.7017)
26          5.073e+00  2.100e-03  y = (cos((x₅ - (x₁ + (x₅ + 1.8771))) - sin(exp(sin(x₅)) - ...
                                      (exp(x₅) * -10.002))) - (2.8191 + (x₅ * x₅))) + 0.071199
29          5.028e+00  2.994e-03  y = cos((exp(cos(cos((x₂ + 0.34185) + ((cos(exp(x₅ + x₀)) ...
                                      * 0.62967) * x₀)) * 0.60883)) + 1.5473) * x₅) - ((x₅ * x₅)...
                                       + 2.7608)
30          4.929e+00  1.991e-02  y = cos((exp(cos(cos(x₂ + ((sin(cos(x₅ + cos(x₀)) * 0.4821...
                                      2) * x₀) + 0.36446)) * 0.7351)) + 1.7941) * x₅) - ((x₅ * x...
                                      ₅) + 2.8096)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_152301_Cc10AP\hall_of_fame.csv

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

Best by score: -x5*x5 - 2.7146783
Index 2, score=3.321948
Equation: -2.7146783 - (x5 * x5)

Index 7, score=0.023898
Equation: cos(x1 * (x2 + -0.79690355)) - ((x5 * x5) + 2.7026815)

Index 17, score=0.019908
Equation: cos((exp(cos(cos(x2 + ((sin(cos(x5 + cos(x0)) * 0.48211518) * x0) + 0.36445895)) * 0.7351048)) + 1.7941412) * x5) - ((x5 * x5) + 2.809645)

In [195]:
model_2_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_2_noisy = model_2_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.133
3           4.394e+03  1.726e-02  y = x₂ + -76.589
5           2.585e+01  2.568e+00  y = -2.8207 - (x₅ * x₅)
7           2.578e+01  1.385e-03  y = -2.8079 - (x₅ * (x₅ - -0.031317))
8           2.538e+01  1.561e-02  y = -2.8703 - ((x₅ * x₅) - cos(x₄))
9           2.499e+01  1.522e-02  y = -2.7327 - ((x₅ * x₅) - (x₀ * 0.10118))
10          2.474e+01  1.009e-02  y = -2.8278 - ((x₅ * x₅) - sin(x₄ * x₅))
12          2.471e+01  5.938e-04  y = (-2.7923 - (x₅ * x₅)) - sin(0.18635 - (x₄ * x₅))
14          2.460e+01  2.183e-03  y = (-2.8924 - (x₅ * x₅)) - sin((x₀ * (-7.2167 - x₅)) * 1....
                                      5286)
15          2.430e+01  1.231e-02  y = sin(x₅ * x₄) + (-1.3047 - ((x₅ * x₅) - (cos(x₄) - 1.51...
                                      4)))
20          2.421e+01  7.776e-04  y = sin(x₅ * cos((x₅ - (x₂ + 0.34998)) + x₂)) + (-2.929 - ...
                                      ((x₅ * x₅) - cos(x₄)))
22          2.390e+01  6.525e-03  y = (-2.9408 - (x₅ * x₅)) - sin(((x₅ * (x₅ * 22.762)) - x₂...
                                      ) - exp(x₄ - sin(x₅ - 1.9291)))
25          2.381e+01  1.244e-03  y = (-2.9408 - (x₅ * x₅)) - (sin((((x₅ * x₅) * 22.762) - x...
                                      ₂) - exp(x₄ - sin(0.94977))) - sin(0.94977 - x₄))
26          2.376e+01  1.910e-03  y = (-2.6815 - (x₅ * x₅)) - (sin((((x₅ * x₅) * 29.493) - x...
                                      ₂) - exp(x₄ - (x₅ - 44.185))) - sin(1.1661 - x₄))
27          2.336e+01  1.702e-02  y = (-2.9408 - (x₅ * x₅)) - (sin(((x₅ * (x₅ * 22.762)) - x...
                                      ₂) - exp(x₄ - sin(x₅ - 1.9291))) - sin(0.94977 - x₄))
28          2.319e+01  7.508e-03  y = (-2.9408 - (x₅ * x₅)) - (sin((((x₅ * x₅) * 22.762) - x...
                                      ₂) - exp(x₄ - sin(x₄ - -1.9941))) - sin(exp(0.11505) - x₄)...
                                      )
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_152304_7bx8az\hall_of_fame.csv
Best by score: -x5*x5 - 2.820656
Index 2, score=2.567903
Equation: -2.820656 - (x5 * x5)

Index 1, score=0.017257
Equation: x2 + -76.58875

Index 14, score=0.017025
Equation: (-2.9408355 - (x5 * x5)) - (sin(((x5 * (x5 * 22.76164)) - x2) - exp(x4 - sin(x5 - 1.9291333))) - sin(0.9497684 - x4))

## 5.5.6 Model 3 with noise

In [196]:
model_3_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_3_noisy = model_3_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.022
3           4.336e+03  1.655e-02  y = x₂ - 76.483
5           5.645e+00  3.322e+00  y = -2.7147 - (x₅ * x₅)
7           5.635e+00  8.623e-04  y = (x₅ * (x₅ * -0.99853)) - 2.8231
9           5.547e+00  7.834e-03  y = (-2.6367 - (x₅ * x₅)) - sin(exp(x₄))
10          5.159e+00  7.258e-02  y = (-2.7365 - (x₅ * x₅)) - sin(x₀ * -1.4504)
12          5.142e+00  1.678e-03  y = -2.7371 - ((x₅ * x₅) - sin((x₀ * 1.4556) + -12.37))
13          5.056e+00  1.687e-02  y = -2.7299 - ((x₅ * x₅) - sin((x₀ * 1.4196) + exp(x₀)))
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: -x5*x5 - 2.7146788
Index 2, score=3.321948
Equation: -2.7146788 - (x5 * x5)

Index 5, score=0.072581
Equation: (-2.7364962 - (x5 * x5)) - sin(x0 * -1.4504236)

Index 7, score=0.016875
Equation: -2.729859 - ((x5 * x5) - sin((x0 * 1.4196415) + exp(x0)))

  - outputs\20250510_152306_QcW1pD\hall_of_fame.csv

In [197]:
model_3_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_3_noisy = model_3_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.133
3           4.394e+03  1.726e-02  y = x₂ + -76.59
5           2.585e+01  2.568e+00  y = -2.8207 - (x₅ * x₅)
7           2.578e+01  1.385e-03  y = ((-0.03127 - x₅) * x₅) + -2.8076
9           2.499e+01  1.541e-02  y = ((x₀ * 0.10117) + -2.7328) - (x₅ * x₅)
10          2.474e+01  1.011e-02  y = (sin(x₄ * x₅) - (x₅ * x₅)) + -2.8037
12          2.430e+01  9.011e-03  y = (-2.8234 - (x₅ * x₅)) + sin((x₅ * 6.5867) + -2.2446)
15          2.390e+01  5.588e-03  y = ((sin(x₅ * x₄) - (x₅ * x₅)) + sin(x₅ * -6.6297)) + -2....
                                      8466
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: -x5*x5 - 2.820656
Index 2, score=2.567903
Equation: -2.820656 - (x5 * x5)

Index 1, score=0.017257
Equation: x2 + -76.58951

Index 4, score=0.015413
Equation: ((x0 * 0.101174295) + -2.732757) - (x5 * x5)

  - outputs\20250510_152309_NeDaRF\hall_of_fame.csv

# 5.6 Output into a DF [4.0]

In [198]:
import pandas as pd

data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5'   
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1,best,x5*(-0.9899335)*x5 + sin(x0 + x1 + x1) - 3.088...,2.031154
1,model_1,3,(x5 * x5) * -1.1931036,2.031154
2,model_1,8,(((x5 * -0.9899335) * x5) + sin(x0 + (x1 + x1)...,0.583093
3,model_1,4,((x5 * x5) * -0.981529) + -3.1631775,0.560019
4,model_2,best,-x5*x5 - sin((x0 + x1)*(-2.000435))*cos(0.0835...,3.142667
5,model_2,3,-3.0127745 - (x5 * x5),3.142667
6,model_2,10,(-2.9872622 - (x5 * x5)) - (sin((x1 + x0) * -2...,0.094392
7,model_2,9,-2.9659462 - ((x5 * x5) - sin((x0 + (cos(x1) *...,0.083551
8,model_3,best,-x5*x5 - 3.0128005,3.201109
9,model_3,3,-3.0128005 - (x5 * x5),3.201109
10,model_3,9,((x5 * (x5 * -0.9820347)) + (sin(x1 + x1) * -0...,0.039329
11,model_3,7,((x5 * (x5 * -0.9773174)) + -3.1972888) + (sin...,0.031284
12,model_1_noisy,best,x5*x5*(-0.9798246) - 3.1116507,2.018258
13,model_1_noisy,3,(x5 * -1.1879799) * x5,2.018258
14,model_1_noisy,4,(x5 * (x5 * -0.9798246)) + -3.1116507,0.514755
15,model_1_noisy,2,cos(x5) + -10.922028,0.074934
16,model_2_noisy,best,-x5*x5 + sin(x0 + x1 + x1) + sin(x0 + x1 + x1)...,3.038596
17,model_2_noisy,3,-2.9470925 - (x5 * x5),3.038596
18,model_2_noisy,7,(-2.9414787 - (x5 * x5)) + sin(x1 + (x0 + x1)),0.963023
19,model_2_noisy,9,((-2.844277 - (x5 * x5)) + sin(x1 + (x1 + x0))...,0.260538
20,model_3_noisy,best,-x5*x5 + sin(x0 + x1 + x1) - 2.9413362,3.096697
21,model_3_noisy,3,-2.9472663 - (x5 * x5),3.096697
22,model_3_noisy,8,(-2.9413362 - (x5 * x5)) + sin((x0 + x1) + x1),0.953158
23,model_3_noisy,6,(sin(x1 * -2.024923) + -3.0127091) - (x5 * x5),0.031051
24,model_1_wide_range,best,x5*(-0.9992922)*x5 - 3.028511,3.273026
25,model_1_wide_range,2,(x5 * x5) * -1.0218042,3.273026
26,model_1_wide_range,3,((x5 * -0.9992922) * x5) + -3.028511,0.554636
27,model_1_wide_range,8,(((x5 * x5) + 2.1640432) + cos(cos(x1 + exp(co...,0.044949
28,model_2_wide_range,best,-x5*x5 - sin(x0 + x1 - (-x1 - 21.968521)) - 2....,3.827115
29,model_2_wide_range,2,-2.9764159 - (x5 * x5),3.827115
30,model_2_wide_range,8,(-2.985921 - (x5 * x5)) - sin((x0 - (-21.96852...,1.173122
31,model_2_wide_range,1,x2 + -76.745255,0.016651
32,model_3_wide_range,best,-x5*x5 - 2.9763682,3.827115
33,model_3_wide_range,2,-2.9763682 - (x5 * x5),3.827115
34,model_3_wide_range,7,((sin(x4 * x4) * -0.40875223) + -2.938439) - (...,0.017249
35,model_3_wide_range,1,x2 + -76.74523,0.016651
36,model_1_noisy_std_dev_2,best,x5*x5*(-0.99853265) - 2.822184,3.074411
37,model_1_noisy_std_dev_2,2,x5 * (x5 * -1.0195066),3.074411
38,model_1_noisy_std_dev_2,3,(x5 * (x5 * -0.99853265)) + -2.822184,0.248400
39,model_1_noisy_std_dev_2,6,sin(x0 * 1.4497756) + (((x5 * -0.99840003) * x...,0.073948
40,model_2_noisy_std_dev_2,best,-x5*x5 - 2.7146783,3.321948
41,model_2_noisy_std_dev_2,2,-2.7146783 - (x5 * x5),3.321948
42,model_2_noisy_std_dev_2,7,cos(x1 * (x2 + -0.79690355)) - ((x5 * x5) + 2....,0.023898
43,model_2_noisy_std_dev_2,17,cos((exp(cos(cos(x2 + ((sin(cos(x5 + cos(x0)) ...,0.019908
44,model_3_noisy_std_dev_2,best,-x5*x5 - 2.7146788,3.321948
45,model_3_noisy_std_dev_2,2,-2.7146788 - (x5 * x5),3.321948
46,model_3_noisy_std_dev_2,5,(-2.7364962 - (x5 * x5)) - sin(x0 * -1.4504236),0.072581
47,model_3_noisy_std_dev_2,7,-2.729859 - ((x5 * x5) - sin((x0 * 1.4196415) ...,0.016875
48,model_1_noisy_std_dev_5,best,x5*x5*(-1.0226563),2.514830
49,model_1_noisy_std_dev_5,2,x5 * (x5 * -1.0226563),2.514830
50,model_1_noisy_std_dev_5,3,(x5 * (x5 * -1.0037103)) + -2.5486856,0.054270
51,model_1_noisy_std_dev_5,1,x2 + -76.58875,0.017257
52,model_2_noisy_std_dev_5,best,-x5*x5 - 2.820656,2.567903
53,model_2_noisy_std_dev_5,2,-2.820656 - (x5 * x5),2.567903
54,model_2_noisy_std_dev_5,1,x2 + -76.58875,0.017257
55,model_2_noisy_std_dev_5,14,(-2.9408355 - (x5 * x5)) - (sin(((x5 * (x5 * 2...,0.017025
56,model_3_noisy_std_dev_5,best,-x5*x5 - 2.820656,2.567903
57,model_3_noisy_std_dev_5,2,-2.820656 - (x5 * x5),2.567903
58,model_3_noisy_std_dev_5,1,x2 + -76.58951,0.017257
59,model_3_noisy_std_dev_5,4,((x0 * 0.101174295) + -2.732757) - (x5 * x5),0.015413

In [199]:
df.to_csv('results4.csv')

In [200]:
data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5'   
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

In [201]:
df.to_csv('results4_only_best.csv')

In [202]:
from pysr import jl
jl.seval("using Primes: prime")

In [203]:
%julia using Primes: prime

In [204]:
jl.seval(
    """
function p(i::T) where T
    if 0.5 < i < 1000
        return T(prime(round(Int, i)))
    else
        return T(NaN)
    end
end
"""
)

p (generic function with 1 method)

In [205]:
%%julia
function p(i::T) where T
    if 0.5 < i < 1000
        return T(prime(round(Int, i)))
    else
        return T(0.0)
    end
end

p (generic function with 1 method)

In [206]:
primes = {i: jl.p(i * 1.0) for i in range(0, 999)}

# 5.7 Function f [5.0]

$$f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$$

- X (random values  $\mathbb{R}^6$ [-5, 5])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev = 0.5)

In [207]:

np.random.seed(0)
X = np.random.uniform(-5, 5, size=(200, 6))
# y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 2
y = [2.2*sin(X[:, 0] + 2*X[:, 1]) - X[:, 5] ** 2 - primes[np.abs(int(X[i, 0]))] for i in range(200)]
# Add the y samples with random noise
noise = np.random.normal(loc=0.0, scale=0.5, size=len(y))
y_noisy = y + noise

In [ ]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

:

# 5.8 Experiments [5.0]

## 5.8.1 Model 1

In [209]:
import sympy
class sympy_p(sympy.Function):
    pass

model_1f = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    extra_sympy_mappings={"p": sympy_p},
    maxsize=20,
    **default_pysr_params,
)

model_1f_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    extra_sympy_mappings={"p": sympy_p},
    maxsize=20,
    **default_pysr_params,
)

model_1f.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 2.240e+02
Progress: 2 / 180000 total iterations (0.001%)
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 1
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 2
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 3
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 4
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 5
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 6
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 7
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 8
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 9
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 10
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 11
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 12
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 13
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 14
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 15
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 16
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 17
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 18
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 19
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 20
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 21
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 22
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 23
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 24
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 25
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 26
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 27
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 28
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 29
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 30
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 31
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 32
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 33
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 34
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 35
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 36
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 37
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 38
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 39
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 40
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 41
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 42
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 43
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 44
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 45
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 46
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 47
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 48
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 49
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 50
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 51
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 52
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 53
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Best equations for output 54

:

:

### Model 1 best + top3 according to score

In [ ]:
best_equation_1 = model_1f.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1f.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x5*x5*(-0.98154604) - 3.163106
Index 3, score=2.031154
Equation: (x5 * x5) * -1.1931325

Index 4, score=0.560019
Equation: (x5 * (x5 * -0.98154604)) + -3.163106

Index 2, score=0.073704
Equation: cos(x5) + -10.987488

## 5.8.2 Model 2

Added constraint to operator "^" - safe_pow

In [ ]:
def safe_pow(x, y):
    if x < 0 and np.floor(y) != y:
        return np.nan
    return np.power(x, y)

model_2f = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2f_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2f.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.159
3           5.537e+01  2.051e-03  y = -11.021 - x₅
4           5.152e+01  7.208e-02  y = cos(x₅) - 10.987
5           2.224e+00  3.143e+00  y = -3.0129 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = (x₅ * (x₅ * -0.98154)) - 3.1631
9           2.194e+00  2.514e-03  y = (-2.9964 - (x₀ * -0.05681)) - (x₅ * x₅)
11          2.132e+00  1.432e-02  y = ((x₅ + (x₄ * -0.035437)) * (x₅ * -0.97745)) - 3.1981
13          2.120e+00  2.745e-03  y = ((((x₄ * -0.035437) + x₅) * (x₅ + 0.038744)) * -0.9774...
                                      5) - 3.1981
14          6.613e-01  1.165e+00  y = (-3.0203 - cos(x₀ - ((x₁ - -0.79503) * -2.003))) - (x₅...
                                       * x₅)
16          6.599e-01  1.023e-03  y = (-3.0105 - cos(x₀ - ((x₁ - -0.79435) * -2.002))) - (x₅...
                                       * (x₅ - -0.012896))
18          6.565e-01  2.642e-03  y = (-3.0203 - cos(x₀ - ((x₁ - -0.79503) * -2.003))) - ((x...
                                      ₅ * x₅) + (x₁ * 0.033666))
19          6.538e-01  4.064e-03  y = (-3.0203 - cos(x₀ - ((x₁ - -0.79503) * -2.003))) - ((s...
                                      in(x₀) * 0.033666) + (x₅ * x₅))
20          6.511e-01  4.143e-03  y = ((-3.0105 - cos(x₀ - ((x₁ - -0.79435) * -2.002))) - ((...
                                      x₅ - -0.012896) * x₅)) + (x₀ * 0.024809)
22          6.451e-01  4.617e-03  y = (-3.0105 - cos(x₀ - ((x₁ - -0.79435) * -2.002))) - (((...
                                      x₅ - -0.012896) * x₅) + ((x₁ - x₀) * 0.024809))
26          6.289e-01  6.367e-03  y = (-3.0203 - cos(x₀ - ((x₁ - -0.79503) * -2.003))) - ((s...
                                      in(cos(x₀ - ((x₁ - -0.79503) * -2.003))) * 0.033666) + (x₅...
                                       * x₅))
27          2.012e-02  3.442e+00  y = ((-3.0203 - cos(x₀ - ((x₁ - -0.79503) * -2.003))) - co...
                                      s(x₀ - ((x₁ - -0.79503) * -2.003))) - ((x₅ * x₅) - (-0.061...
                                      815 * -0.79503))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.158516
	1         0.002051                                    -11.020784 - x5
	2         0.072084                                cos(x5) - 10.987488
	3         3.142667                             -3.0128691 - (x5 * x5)
	4         0.004262                 (x5 * (x5 * -0.981545)) - 3.163129
	5         0.002514      (-2.9964285 - (x0 * -0.05681007)) - (x5 * x5)
	6         0.014322  ((x5 + (x4 * -0.03543666)) * (x5 * -0.9774493)...
	7         0.002745  ((((x4 * -0.03543666) + x5) * (x5 + 0.03874399...
	8         1.165197  (-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2...
	9         0.001023  (-3.01047 - cos(x0 - ((x1 - -0.79435456) * -2....
	10        0.002642  (-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2...
	11        0.004064  (-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2...
	12        0.004143  ((-3.01047 - cos(x0 - ((x1 - -0.79435456) * -2...
	13        0.004617  (-3.01047 - cos(x0 - ((x1 - -0.79435456) * -2....
	14        0.006367  (-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2...
	15  >>>>  3.442063  ((-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -...

	         loss  complexity
	0   55.599796           1
	1   55.372204           3
	2   51.521240           4
	3    2.224043           5
	4    2.205166           7
	5    2.194107           9
	6    2.132152          11
	7    2.120477          13
	8    0.661295          14
	9    0.659943          16
	10   0.656465          18
	11   0.653803          19
	12   0.651100          20
	13   0.645115          22
	14   0.628893          26
	15   0.020124          27
]

  - outputs\20250510_133001_UtWRwD\hall_of_fame.csv

In [ ]:
best_equation_2 = model_2f.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2f.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -(x5*x5 - (-1)*(-0.7950349)*0.061814636) - cos(x0 - (-2.0029647)*(x1 - 1*(-0.7950349))) - cos(x0 - (-2.0029647)*(x1 - 1*(-0.7950349))) - 3.0203273
Index 15, score=3.442063
Equation: ((-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2.0029647))) - cos(x0 - ((x1 - -0.7950349) * -2.0029647))) - ((x5 * x5) - (-0.061814636 * -0.7950349))

Index 3, score=3.142667
Equation: -3.0128691 - (x5 * x5)

Index 8, score=1.165197
Equation: (-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2.0029647))) - (x5 * x5)

## 5.8.3 Model 3

In [ ]:
model_3f = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3f_noisy = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3f.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  1.594e+01  y = -11.158
3           5.537e+01  2.051e-03  y = -11.021 - x₅
4           5.462e+01  1.364e-02  y = -11.157 - sin(x₀)
5           2.224e+00  3.201e+00  y = -3.0128 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = -3.1631 - ((x₅ * 0.98155) * x₅)
9           2.153e+00  1.189e-02  y = (((x₄ * 0.03329) - x₅) * x₅) - 3.0191
10          2.134e+00  9.020e-03  y = (-3.0123 - (x₅ * x₅)) + (sin(x₀) * -0.41058)
11          2.133e+00  4.447e-04  y = (-3.0114 - (x₅ * x₅)) + (sin(sin(x₀)) * -0.47021)
12          2.106e+00  1.284e-02  y = (((sin(x₀) * -0.44337) + -3.2709) - (x₅ * x₅)) * 0.977...
                                      35
13          2.099e+00  3.037e-03  y = (-3.0123 - (x₅ * x₅)) + sin(sin(x₀ * (0.81933 + x₁)))
14          1.707e+00  2.068e-01  y = -2.9841 - (((sin(x₁) * sin(x₁)) * sin(x₀)) + (x₅ * x₅)...
                                      )
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133004_LotbFM\hall_of_fame.csv

[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -11.158203
	1         0.002051                                    -11.020794 - x5
	2         0.013642                               -11.157449 - sin(x0)
	3   >>>>  3.201109                             -3.0128005 - (x5 * x5)
	4         0.004262              -3.1631155 - ((x5 * 0.98154515) * x5)
	5         0.011890       (((x4 * 0.033289738) - x5) * x5) - 3.0191004
	6         0.009021  (-3.0123389 - (x5 * x5)) + (sin(x0) * -0.41058...
	7         0.000445  (-3.01142 - (x5 * x5)) + (sin(sin(x0)) * -0.47...
	8         0.012839  (((sin(x0) * -0.44336697) + -3.2709334) - (x5 ...
	9         0.003038  (-3.0123389 - (x5 * x5)) + sin(sin(x0 * (0.819...
	10        0.206831  -2.984116 - (((sin(x1) * sin(x1)) * sin(x0)) +...

	         loss  complexity
	0   55.599790           1
	1   55.372204           3
	2   54.621952           4
	3    2.224043           5
	4    2.205166           7
	5    2.153344           9
	6    2.134007          10
	7    2.133058          11
	8    2.105847          12
	9    2.099460          13
	10   1.707190          14
]

In [ ]:
best_equation_3 = model_3f.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3f.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 3.0128005
Index 3, score=3.201109
Equation: -3.0128005 - (x5 * x5)

Index 10, score=0.206831
Equation: -2.984116 - (((sin(x1) * sin(x1)) * sin(x0)) + (x5 * x5))

Index 2, score=0.013642
Equation: -11.157449 - sin(x0)

## 5.8.4 Model 1 with noise

In [ ]:
model_1f_noisy.fit(X, y_noisy)
best_equation_1_noisy = model_1f_noisy.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1f_noisy.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.094
3           5.560e+01  5.027e-04  y = x₂ + -11.245
4           5.159e+01  7.493e-02  y = cos(x₅) + -10.922
5           6.855e+00  2.018e+00  y = x₅ * (x₅ * -1.188)
7           2.449e+00  5.148e-01  y = ((x₅ * x₅) * -0.97982) + -3.1117
9           2.434e+00  2.937e-03  y = (((x₅ * -0.97674) + -0.04277) * x₅) + -3.1309
11          2.415e+00  3.898e-03  y = ((x₀ * 0.059929) + (x₅ * (x₅ * -0.9786))) + -3.1043
12          2.340e+00  3.182e-02  y = ((x₅ * (x₅ * -0.98091)) + sin(x₁ * -2.0207)) + -3.1691
14          2.339e+00  1.214e-04  y = (sin(x₁ * -2.0207) + (x₅ * ((x₅ * -0.98031) + -0.00851...
                                      56))) + -3.1729
16          2.318e+00  4.442e-03  y = ((x₀ * 0.047973) + ((x₅ * (x₅ * -0.97998)) + sin(x₁ * ...
                                      -2.0232))) + -3.1624
17          2.232e+00  3.789e-02  y = (sin(x₀) * -0.45105) + (sin(x₁ * -2.0127) + (((x₅ * x₅...
                                      ) * -0.97644) + -3.2067))
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: x5*x5*(-0.97982454) - 3.1116526
Index 3, score=2.018258
Equation: x5 * (x5 * -1.1879799)

Index 4, score=0.514755
Equation: ((x5 * x5) * -0.97982454) + -3.1116526

Index 2, score=0.074934
Equation: cos(x5) + -10.921997

  - outputs\20250510_133006_lF47a0\hall_of_fame.csv

## 5.8.5 Model 2 with noise

In [ ]:
model_2f_noisy.fit(X, y_noisy)
best_equation_2_noisy = model_2f_noisy.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2f_noisy.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.092
3           5.528e+01  3.374e-03  y = -10.955 - x₅
4           5.159e+01  6.919e-02  y = cos(x₅) + -10.922
5           2.471e+00  3.039e+00  y = -2.9473 - (x₅ * x₅)
7           2.449e+00  4.586e-03  y = -3.1116 - ((x₅ * x₅) * 0.97983)
9           2.434e+00  2.937e-03  y = -3.1309 - (((x₅ + 0.043784) * x₅) * 0.97674)
12          2.347e+00  1.218e-02  y = (((x₅ * (x₅ + x₅)) + sin(x₀)) * -0.48744) - 3.1514
13          2.345e+00  6.197e-04  y = (((x₅ * (x₅ + x₅)) + sin(sin(x₀))) - -6.4105) * -0.488...
                                      49
16          2.332e+00  1.956e-03  y = -1.6727 - (((-3.0488 - ((x₅ + x₅) * x₅)) + cos(x₅ * -6...
                                      .0988)) * -0.48545)
18          2.322e+00  1.989e-03  y = -3.1526 - ((((0.33804 - ((x₅ + x₅) + 0.40742)) * x₅) +...
                                       cos(x₅ * -6.0988)) * -0.48546)
19          2.314e+00  3.705e-03  y = -3.0569 - ((cos((cos(x₅ * -6.1207) + 1.4845) + x₀) - (...
                                      (x₅ + x₅) * x₅)) * -0.4914)
22          2.312e+00  3.299e-04  y = -1.6727 - ((0.40653 + ((-3.0488 - (((x₅ + x₅) + (x₄ * ...
                                      -0.10097)) * x₅)) + cos(x₅ * -6.0988))) * -0.48545)
23          2.271e+00  1.788e-02  y = (((sin(((x₅ + -2.5165) * (exp(x₄) + -0.54693)) + 1.580...
                                      1) + ((x₅ + x₅) * x₅)) + 2.6768) * -0.49146) + -1.704
25          2.271e+00  2.682e-07  y = (((sin(((x₅ + -2.5165) * (exp(x₄) + -0.54779)) + 1.574...
                                      7) + (((x₅ + x₅) * x₅) + 2.7654)) * -0.49147) + -1.8808) -...
                                       -0.22074
28          2.254e+00  2.492e-03  y = -0.48706 * (((x₅ * (x₅ + x₅)) + cos((x₅ + -2.0375) * (...
                                      sin((x₁ - x₅) * (exp(x₄ - 1.1806) + -0.053269)) + x₅))) + ...
                                      6.3868)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133008_LH45I0\hall_of_fame.csv
Best by score: -x5*x5 - 2.9473116
Index 3, score=3.038596
Equation: -2.9473116 - (x5 * x5)

Index 2, score=0.069191
Equation: cos(x5) + -10.922013

Index 12, score=0.017876
Equation: (((sin(((x5 + -2.5165377) * (exp(x4) + -0.54692554)) + 1.5800674) + ((x5 + x5) * x5)) + 2.6768017) * -0.49146432) + -1.7039533

## 5.8.6 Model 3 with noise

In [ ]:
model_3f_noisy.fit(X, y_noisy)
best_equation_3_noisy = model_3f_noisy.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3f_noisy.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  1.594e+01  y = -11.093
3           5.528e+01  3.374e-03  y = -10.955 - x₅
4           5.467e+01  1.109e-02  y = -11.092 - sin(x₀)
5           2.471e+00  3.097e+00  y = -2.9473 - (x₅ * x₅)
7           2.449e+00  4.586e-03  y = (x₅ * (x₅ * -0.97982)) - 3.1117
9           2.414e+00  7.170e-03  y = -3.1116 - ((x₅ + (x₄ * -0.03746)) * x₅)
11          2.363e+00  1.062e-02  y = (((x₅ + (x₄ * -0.03746)) * x₅) * -0.97839) + -3.1303
12          2.363e+00  1.019e-05  y = ((x₅ + sin(x₄ * -0.037625)) * (x₅ * -0.9784)) + -3.130...
                                      3
13          2.344e+00  7.932e-03  y = (((x₄ * -0.03855) + x₅) * ((x₅ * -0.97483) - 0.048912)...
                                      ) + -3.1528
14          2.344e+00  9.656e-06  y = ((x₅ + sin(x₄ * -0.038725)) * ((x₅ * -0.97484) - 0.048...
                                      907)) + -3.1528
15          2.344e+00  9.418e-06  y = (((x₅ * -0.97487) - 0.048905) * (x₅ + sin(sin(x₄ * -0....
                                      038928)))) + -3.1528
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133010_DP4rpk\hall_of_fame.csv
Best by score: -x5*x5 - 2.9473026
Index 3, score=3.096697
Equation: -2.9473026 - (x5 * x5)

Index 2, score=0.011090
Equation: -11.091977 - sin(x0)

Index 6, score=0.010619
Equation: (((x5 + (x4 * -0.03746015)) * x5) * -0.97839224) + -3.1302588

# 5.9 Output into a DF [5.0: 3.0]

In [ ]:
import pandas as pd

data = []

for model_name in ['model_1f', 'model_2f', 'model_3f','model_1f_noisy', 'model_2f_noisy', 'model_3f_noisy']:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1,best,x5*x5*(-0.98154604) - 3.163106,2.031154
1,model_1,3,(x5 * x5) * -1.1931325,2.031154
2,model_1,4,(x5 * (x5 * -0.98154604)) + -3.163106,0.560019
3,model_1,2,cos(x5) + -10.987488,0.073704
4,model_2,best,-(x5*x5 - (-1)*(-0.7950349)*0.061814636) - cos...,3.442063
5,model_2,15,((-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -...,3.442063
6,model_2,3,-3.0128691 - (x5 * x5),3.142667
7,model_2,8,(-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2...,1.165197
8,model_3,best,-x5*x5 - 3.0128005,3.201109
9,model_3,3,-3.0128005 - (x5 * x5),3.201109
10,model_3,10,-2.984116 - (((sin(x1) * sin(x1)) * sin(x0)) +...,0.206831
11,model_3,2,-11.157449 - sin(x0),0.013642
12,model_1_noisy,best,x5*x5*(-0.97982454) - 3.1116526,2.018258
13,model_1_noisy,3,x5 * (x5 * -1.1879799),2.018258
14,model_1_noisy,4,((x5 * x5) * -0.97982454) + -3.1116526,0.514755
15,model_1_noisy,2,cos(x5) + -10.921997,0.074934
16,model_2_noisy,best,-x5*x5 - 2.9473116,3.038596
17,model_2_noisy,3,-2.9473116 - (x5 * x5),3.038596
18,model_2_noisy,2,cos(x5) + -10.922013,0.069191
19,model_2_noisy,12,(((sin(((x5 + -2.5165377) * (exp(x4) + -0.5469...,0.017876
20,model_3_noisy,best,-x5*x5 - 2.9473026,3.096697
21,model_3_noisy,3,-2.9473026 - (x5 * x5),3.096697
22,model_3_noisy,2,-11.091977 - sin(x0),0.011090
23,model_3_noisy,6,(((x5 + (x4 * -0.03746015)) * x5) * -0.9783922...,0.010619

In [ ]:
df.to_csv('results5_for3.csv')

# 5.10 Function f [5.0: 4.0]

$$f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$$

- X (random values  $\mathbb{R}^6$ [-15, 15])
- y (values without noise) 
- y_noisy (values with noise with mean = 0.0 and std_dev1 = 2, std_dev2 = 5)

In [ ]:
from numpy import sin, cos, exp, log, sqrt
# Dataset

np.random.seed(0)
X = np.random.uniform(-15, 15, size=(200, 6))
# y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 2
y = [2.2*sin(X[:, 0] + 2*X[:, 1]) - X[:, 5] ** 2 - jl.p(int(X[i, 0]) * 1.0) for i in range(200)]
# Add the y samples with random noise
noise1 = np.random.normal(loc=0.0, scale=2, size=len(y))
y_noisy1 = y + noise1
noise2 = np.random.normal(loc=0.0, scale=5, size=len(y))
y_noisy2 = y + noise2

In [ ]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
)

# 5.11 Experiments [5.0]

## 5.11.1 Model 1

In [ ]:
model_1f_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1f_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1f_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)

model_1f_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.289
3           4.338e+03  1.665e-02  y = x₂ + -76.745
5           6.228e+00  3.273e+00  y = x₅ * (x₅ * -1.0218)
7           2.054e+00  5.546e-01  y = (x₅ * (x₅ * -0.99929)) + -3.0285
9           2.022e+00  7.920e-03  y = ((x₅ + -0.021392) * (x₅ * -0.99981)) + -2.9996
12          1.997e+00  4.119e-03  y = ((x₅ * (x₅ + (cos(x₃) * -0.040072))) * -0.99963) + -3....
                                      0105
13          1.959e+00  1.925e-02  y = ((x₅ + (cos(exp(x₄)) * -0.043225)) * (x₅ * -0.99989)) ...
                                      + -2.9933
14          1.941e+00  9.093e-03  y = (((x₅ * -0.99945) * x₅) + -3.6752) + sin(exp(sin(x₂ * ...
                                      4.2217)))
16          1.923e+00  4.800e-03  y = (sin(sin(exp(x₅ * -1.0461) * -10.061)) + -2.9474) + ((...
                                      x₅ * x₅) * -0.99971)
17          1.923e+00  4.608e-05  y = ((x₅ * x₅) * -1.0005) + (sin(sin(sin(exp(x₅ * -1.0575)...
                                       * -10.059))) + -2.8508)
18          1.916e+00  3.416e-03  y = (sin(sin((exp(x₅ * -1.0575) * -10.059) + 0.092075)) + ...
                                      ((x₅ * x₅) * -1.0005)) + -2.9429
19          1.906e+00  5.275e-03  y = (sin(sin(sin((exp(x₅ * -1.0575) * -10.059) + 0.092075)...
                                      )) + ((x₅ * x₅) * -1.0005)) + -2.9429
20          1.883e+00  1.223e-02  y = -2.9429 + (((x₅ * x₅) * -1.0005) + sin(sin(sin((exp(-1...
                                      .0575 * x₅) * -10.059) + exp(-1.3085)))))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133012_ICirgS\hall_of_fame.csv

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                          -76.28898
	1         0.016651                                    x2 + -76.745125
	2         3.273026                             x5 * (x5 * -1.0218029)
	3   >>>>  0.554636               (x5 * (x5 * -0.9992922)) + -3.028511
	4         0.007920  ((x5 + -0.02139206) * (x5 * -0.99980634)) + -2...
	5         0.004119  ((x5 * (x5 + (cos(x3) * -0.040072292))) * -0.9...
	6         0.019247  ((x5 + (cos(exp(x4)) * -0.043224953)) * (x5 * ...
	7         0.009093  (((x5 * -0.99944854) * x5) + -3.6751559) + sin...
	8         0.004800  (sin(sin(exp(x5 * -1.0460858) * -10.0606)) + -...
	9         0.000046  ((x5 * x5) * -1.0004921) + (sin(sin(sin(exp(x5...
	10        0.003416  (sin(sin((exp(x5 * -1.0574919) * -10.058729) +...
	11        0.005275  (sin(sin(sin((exp(x5 * -1.0574919) * -10.05872...
	12        0.012235  -2.9428918 + (((x5 * x5) * -1.0004921) + sin(s...

	           loss  complexity
	0   4484.837400           1
	1   4337.941400           3
	2      6.228301           5
	3      2.054086           7
	4      2.021807           9
	5      1.996978          12
	6      1.958909          13
	7      1.941177          14
	8      1.922632          16
	9      1.922543          17
	10     1.915988          18
	11     1.905907          19
	12     1.882730          20
]

### Model 1 best + top3 according to score

In [ ]:
best_equation_1 = model_1f_wide_range.sympy()
print("Best by score:", best_equation_1)


top3_1 = model_1f_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_1.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: x5*x5*(-0.9992922) - 3.028511
Index 2, score=3.273026
Equation: x5 * (x5 * -1.0218029)

Index 3, score=0.554636
Equation: (x5 * (x5 * -0.9992922)) + -3.028511

Index 6, score=0.019247
Equation: ((x5 + (cos(exp(x4)) * -0.043224953)) * (x5 * -0.99989194)) + -2.9932628

## 5.11.2 Model 2

Added constraint to operator "^" - safe_pow

In [ ]:
def safe_pow(x, y):
    if x < 0 and np.floor(y) != y:
        return np.nan
    return np.power(x, y)

model_2f_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2f_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2f_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["cos", "exp", "sin", "log"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=30,
    **default_pysr_params,
)

model_2f_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.289
3           4.338e+03  1.665e-02  y = x₂ + -76.745
5           2.056e+00  3.827e+00  y = -2.9766 - (x₅ * x₅)
7           2.022e+00  8.427e-03  y = (x₅ * (0.021677 - x₅)) - 2.9856
9           2.022e+00  4.003e-05  y = -2.9995 - ((x₅ * (0.021389 - x₅)) * -0.99981)
10          2.017e+00  2.292e-03  y = -2.9974 - ((x₅ - (sin(x₄) * -0.031745)) * x₅)
11          2.016e+00  4.257e-04  y = -2.9974 - (x₅ * (x₅ - (sin(sin(x₄)) * -0.031745)))
12          1.984e+00  1.603e-02  y = (x₅ * (0.02013 - (x₅ - (sin(x₃) * 0.032212)))) - 3.014...
                                      8
13          1.980e+00  2.295e-03  y = -1.9439 - (safe_pow(1.4762, sin(exp(x₅))) - (x₅ * (0.0...
                                      23913 - x₅)))
14          1.913e+00  3.438e-02  y = ((x₅ * (0.013511 - x₅)) - (sin(x₂ + x₃) * 0.50496)) - ...
                                      3.0153
17          1.884e+00  5.004e-03  y = (((0.013941 - x₅) - (sin((x₃ - sin(x₁)) + 1.0356) * -0...
                                      .065035)) * x₅) - 2.9987
19          1.884e+00  1.633e-04  y = (((0.013941 - x₅) - (sin(1.0356 + (x₃ - sin(x₁ + -0.62...
                                      433))) * -0.065035)) * x₅) - 2.9987
23          1.804e+00  1.086e-02  y = (((0.015797 - x₅) - (sin(sin(cos(x₅ * -1.8607) + ((x₃ ...
                                      - sin(x₁)) + 0.87852))) * -0.094648)) * x₅) - 3.021
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133014_0O8SKO\hall_of_fame.csv

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	    pick     score                                           equation  \
	0         0.000000                                         -76.288925
	1         0.016651                                     x2 + -76.74522
	2   >>>>  3.827115                             -2.9765701 - (x5 * x5)
	3         0.008427               (x5 * (0.02167654 - x5)) - 2.9855618
	4         0.000040  -2.9995186 - ((x5 * (0.021388775 - x5)) * -0.9...
	5         0.002292  -2.9973736 - ((x5 - (sin(x4) * -0.03174465)) *...
	6         0.000426  -2.9973736 - (x5 * (x5 - (sin(sin(x4)) * -0.03...
	7         0.016027  (x5 * (0.02012969 - (x5 - (sin(x3) * 0.0322119...
	8         0.002295  -1.9439019 - (safe_pow(1.4761515, sin(exp(x5))...
	9         0.034384  ((x5 * (0.013510874 - x5)) - (sin(x2 + x3) * 0...
	10        0.005004  (((0.013940909 - x5) - (sin((x3 - sin(x1)) + 1...
	11        0.000163  (((0.013940909 - x5) - (sin(1.0355971 + (x3 - ...
	12        0.010863  (((0.015797224 - x5) - (sin(sin(cos(x5 * -1.86...

	           loss  complexity
	0   4484.837400           1
	1   4337.941400           3
	2      2.056337           5
	3      2.021969           7
	4      2.021807           9
	5      2.017178          10
	6      2.016319          11
	7      1.984261          12
	8      1.979712          13
	9      1.912798          14
	10     1.884299          17
	11     1.883684          19
	12     1.803589          23
]

In [ ]:
best_equation_2 = model_2f_wide_range.sympy()
print("Best by score:", best_equation_2)


top3_2 = model_2f_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_2.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 2.9765701
Index 2, score=3.827115
Equation: -2.9765701 - (x5 * x5)

Index 9, score=0.034384
Equation: ((x5 * (0.013510874 - x5)) - (sin(x2 + x3) * 0.5049631)) - 3.0153282

Index 1, score=0.016651
Equation: x2 + -76.74522

## 5.11.3 Model 3

In [ ]:
model_3f_wide_range = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3f_noisy_std_dev_2 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3f_noisy_std_dev_5 = PySRRegressor(
    niterations=30,
    binary_operators=["+", "*", "-", "safe_pow(x, y) = x^y"],
    unary_operators=["exp", "sin"],
    extra_sympy_mappings={"safe_pow": lambda x, y: sympy.Pow(x, y)},
    maxsize=15,
    **default_pysr_params,
)

model_3f_wide_range.fit(X, y)

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.485e+03  1.594e+01  y = -76.292
3           4.338e+03  1.665e-02  y = x₂ + -76.745
5           2.056e+00  3.827e+00  y = -2.977 - (x₅ * x₅)
7           2.022e+00  8.427e-03  y = ((0.021677 - x₅) * x₅) - 2.9856
9           2.022e+00  4.026e-05  y = (x₅ * (0.021394 - (x₅ * 0.99981))) - 2.9996
11          2.005e+00  4.133e-03  y = ((x₅ - (x₁ * -0.0017115)) * (0.019323 - x₅)) + -2.9882
12          6.141e-01  1.183e+00  y = -3.0351 - ((x₅ * x₅) - sin(x₀ + (x₁ + x₁)))
14          6.118e-01  1.871e-03  y = -2.9663 - (((x₅ * x₅) - sin((x₁ + x₁) + x₀)) + 0.02094...
                                      1)
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133017_ljCZ5A\hall_of_fame.csv

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

PySRRegressor.equations_ = [
	   pick     score                                           equation  \
	0        0.000000                                          -76.29248
	1        0.016651                                    x2 + -76.745186
	2        3.827115                             -2.9769638 - (x5 * x5)
	3        0.008427               ((0.021677315 - x5) * x5) - 2.985569
	4        0.000040  (x5 * (0.021393938 - (x5 * 0.99980634))) - 2.9...
	5        0.004133  ((x5 - (x1 * -0.0017115241)) * (0.019323384 - ...
	6  >>>>  1.183330     -3.0351326 - ((x5 * x5) - sin(x0 + (x1 + x1)))
	7        0.001871  -2.9662995 - (((x5 * x5) - sin((x1 + x1) + x0)...

	          loss  complexity
	0  4484.837400           1
	1  4337.941400           3
	2     2.056337           5
	3     2.021970           7
	4     2.021807           9
	5     2.005164          11
	6     0.614096          12
	7     0.611802          14
]

In [ ]:
best_equation_3 = model_3f_wide_range.sympy()
print("Best by score:", best_equation_3)


top3_3 = model_3f_wide_range.equations_.nlargest(3, "score")

for idx, row in top3_3.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

Best by score: -x5*x5 - 3.0128005
Index 2, score=3.827115
Equation: -2.9769638 - (x5 * x5)

Index 6, score=1.183330
Equation: -3.0351326 - ((x5 * x5) - sin(x0 + (x1 + x1)))

Index 1, score=0.016651
Equation: x2 + -76.745186

## 5.11.4 Model 1 with noise std_dev 2 and 5

In [ ]:
model_1f_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_1_noisy = model_1f_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1f_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.022
3           4.336e+03  1.655e-02  y = x₂ + -76.487
5           9.261e+00  3.074e+00  y = x₅ * (x₅ * -1.0195)
7           5.635e+00  2.484e-01  y = ((x₅ * -0.99853) * x₅) + -2.8224
9           5.631e+00  3.751e-04  y = (x₅ * ((x₅ * -0.99871) + 0.0077253)) + -2.8127
11          5.541e+00  8.079e-03  y = (((x₅ * x₅) + sin(exp(x₄))) * -0.99876) + -2.7276
12          5.147e+00  7.359e-02  y = (((x₅ * x₅) + sin(x₀ * -1.4498)) * -0.9984) + -2.8636
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133018_aNl7st\hall_of_fame.csv

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

Best by score: x5*(-0.9985297)*x5 - 2.822441
Index 2, score=3.074411
Equation: x5 * (x5 * -1.0195066)

Index 3, score=0.248400
Equation: ((x5 * -0.9985297) * x5) + -2.822441

Index 6, score=0.073594
Equation: (((x5 * x5) + sin(x0 * -1.4498099)) * -0.9983978) + -2.8635705

In [ ]:
model_1f_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_1_noisy = model_1f_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_1_noisy)


top3_1_noisy = model_1f_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_1_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.127
3           4.394e+03  1.726e-02  y = x₂ + -76.589
5           2.874e+01  2.515e+00  y = (x₅ * -1.0226) * x₅
7           2.578e+01  5.427e-02  y = ((x₅ * -1.0037) * x₅) + -2.5487
9           2.573e+01  9.792e-04  y = ((x₅ + 0.026661) * (x₅ * -1.0031)) + -2.5849
10          2.532e+01  1.615e-02  y = ((x₅ * (x₅ * -1.0035)) + -2.6162) + cos(x₄)
11          2.495e+01  1.475e-02  y = ((x₅ * (x₅ * -1.003)) + (x₀ * 0.10008)) + -2.511
12          2.467e+01  1.130e-02  y = sin(x₄ * x₅) + ((x₅ * (x₅ * -1.0041)) + -2.5119)
14          2.455e+01  2.487e-03  y = (x₀ * 0.096418) + ((((x₅ * -1.0028) * x₅) + cos(x₄)) +...
                                       -2.58)
15          2.445e+01  4.081e-03  y = (((x₅ * -1.0042) * x₅) + sin(sin(x₅ * x₄) * 2.1258)) +...
                                       -2.4642
16          2.396e+01  2.039e-02  y = (x₀ * 0.096418) + ((x₅ * (x₅ * -1.0028)) + (sin(x₅ * x...
                                      ₄) + -2.58))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

Best by score: x5*(-1.0226468)*x5
Index 2, score=2.514830
Equation: (x5 * -1.0226468) * x5

Index 3, score=0.054270
Equation: ((x5 * -1.0037091) * x5) + -2.5486984

Index 10, score=0.020387
Equation: (x0 * 0.0964179) + ((x5 * (x5 * -1.002817)) + (sin(x5 * x4) + -2.5799537))

  - outputs\20250510_133020_mmY2tz\hall_of_fame.csv

## 5.11.5 Model 2 with noise std_dev 2 and 5

In [ ]:
model_2f_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_2_noisy = model_2f_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2f_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.027
3           4.336e+03  1.655e-02  y = x₂ + -76.483
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.636e+00  7.914e-04  y = (-2.8636 - (x₅ * x₅)) * 0.9984
9           5.558e+00  6.951e-03  y = -2.7397 - ((x₅ * x₅) + sin(exp(x₄)))
10          5.358e+00  3.671e-02  y = -2.7737 - (sin(x₅ * 6.6668) + (x₅ * x₅))
11          5.341e+00  3.061e-03  y = -2.7737 - (sin(sin(x₅ * 6.6668)) + (x₅ * x₅))
12          5.147e+00  3.697e-02  y = -2.8636 - ((sin(x₀ * -1.4498) + (x₅ * x₅)) * 0.9984)
15          5.062e+00  5.569e-03  y = -2.7941 - (cos((cos(x₁ + -0.72545) * 2.5197) + x₀) + (...
                                      x₅ * x₅))
16          4.787e+00  5.592e-02  y = -2.7453 - (cos((x₀ + ((x₁ * 1.9137) + 1.3506)) + 0.280...
                                      81) + (x₅ * x₅))
21          4.391e+00  1.725e-02  y = -2.7194 - (cos(x₀ + ((cos(((x₃ - x₅) + x₁) * -0.045078...
                                      ) + x₁) * 1.9986)) + (x₅ * x₅))
23          4.319e+00  8.286e-03  y = -2.7194 - (cos(x₀ + ((cos(((x₃ - x₅) + (x₅ + -4.2201))...
                                       * -0.045078) + x₁) * 1.9986)) + (x₅ * x₅))
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133022_RzNUoe\hall_of_fame.csv
Best by score: -x5*x5 - 2.7146323
Index 2, score=3.321948
Equation: -2.7146323 - (x5 * x5)

Index 9, score=0.055915
Equation: -2.7452788 - (cos((x0 + ((x1 * 1.9136584) + 1.3505633)) + 0.28081116) + (x5 * x5))

Index 7, score=0.036967
Equation: -2.863597 - ((sin(x0 * -1.4498118) + (x5 * x5)) * 0.9983976)

In [ ]:
model_2f_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_2_noisy = model_2f_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_2_noisy)


top3_2_noisy = model_2f_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_2_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.134
3           4.394e+03  1.726e-02  y = x₂ + -76.59
5           2.585e+01  2.568e+00  y = -2.8206 - (x₅ * x₅)
7           2.578e+01  1.385e-03  y = -2.8077 - (x₅ * (x₅ - -0.03127))
8           2.538e+01  1.561e-02  y = cos(x₄) - ((x₅ * x₅) - -2.8703)
9           2.499e+01  1.522e-02  y = (x₀ * 0.10118) + (-2.7328 - (x₅ * x₅))
10          2.474e+01  1.011e-02  y = sin(x₄ * x₅) - ((x₅ * x₅) - -2.8036)
12          2.445e+01  5.852e-03  y = (-3.0897 - sin((x₅ * x₁) * -4.2154)) - (x₅ * x₅)
13          2.430e+01  6.192e-03  y = sin(x₅ * x₄) + ((cos(x₄) - (x₅ * x₅)) + -2.8535)
14          2.391e+01  1.646e-02  y = (-2.5677 - (x₅ * x₅)) - (sin((x₅ * x₁) * -4.2178) * 1....
                                      9866)
15          2.373e+01  7.347e-03  y = (-2.8513 - (sin(sin((x₁ * x₅) * -4.2165)) * 2.2888)) -...
                                       (x₅ * x₅)
17          2.360e+01  2.846e-03  y = ((-2.7778 - (sin((x₅ * x₁) * -4.2171) * 2.0685)) - (x₅...
                                       * x₅)) - sin(x₄)
18          2.355e+01  2.045e-03  y = ((-2.8343 - (sin(sin(x₅ * (x₁ * -4.2152))) * 2.3274)) ...
                                      - (x₅ * x₅)) - sin(x₄)
19          2.291e+01  2.739e-02  y = sin(x₄ * x₅) + ((-2.5677 - (x₅ * x₅)) - (sin((x₅ * x₁)...
                                       * -4.2178) * 1.9866))
21          2.283e+01  1.820e-03  y = ((-2.5677 - sin((0.3218 * x₅) * x₁)) - (x₅ * x₅)) - (s...
                                      in((x₅ * x₁) * -4.2178) * 1.9866)
22          2.278e+01  2.281e-03  y = (sin(x₅ * x₄) + ((-2.5636 - (sin(sin((x₅ * x₁) * -4.21...
                                      66)) * 2.1524)) - (x₅ * x₅))) - 0.20818
23          2.250e+01  1.200e-02  y = (-2.954 - (sin((x₅ * x₁) * 0.32532) * 2.0368)) - ((x₅ ...
                                      * x₅) - sin(x₅ * ((x₁ * x₄) * -1.9348)))
24          2.239e+01  5.225e-03  y = sin(x₅ * x₄) + (((-2.5679 - (sin(sin((x₁ * x₅) * -4.21...
                                      65) * 1.9872) * 1.7681)) - (x₅ * x₅)) - 0.21265)
28          2.170e+01  7.806e-03  y = (((sin(x₅ * x₄) + -2.5677) - (sin((x₅ * x₁) * 0.3218) ...
                                      * 1.9866)) - (x₅ * x₅)) - (sin((x₅ * x₁) * -4.2178) * 1.98...
                                      66)
30          2.163e+01  1.522e-03  y = ((sin(x₅ * x₄) + ((-2.5677 - (sin(x₅ * (x₁ * 0.3218)) ...
                                      * 1.9866)) - (x₅ * x₅))) - (sin((x₁ * x₅) * -4.2178) * 1.9...
                                      866)) - 0.23553
───────────────────────────────────────────────────────────────────────────────────────────────────
Best by score: -x5*x5 - 2.820567
Index 2, score=2.567903
Equation: -2.820567 - (x5 * x5)

Index 13, score=0.027386
Equation: sin(x4 * x5) + ((-2.5677297 - (x5 * x5)) - (sin((x5 * x1) * -4.217832) * 1.9865578))

Index 1, score=0.017257
Equation: x2 + -76.5897

  - outputs\20250510_133025_x8azlA\hall_of_fame.csv

## 5.11.6 Model 3 with noise

In [ ]:
model_3f_noisy_std_dev_2.fit(X, y_noisy1)
best_equation_3_noisy = model_3f_noisy_std_dev_2.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3f_noisy_std_dev_2.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  1.594e+01  y = -76.022
3           4.336e+03  1.655e-02  y = x₂ + -76.484
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.625e-04  y = (x₅ * (x₅ * -0.99853)) - 2.8226
9           5.631e+00  3.752e-04  y = ((x₅ * (x₅ + -0.0077526)) * -0.99871) - 2.8123
11          5.541e+00  8.060e-03  y = ((x₅ * (x₅ * -0.99878)) + -2.7268) - sin(exp(x₄))
12          5.228e+00  5.816e-02  y = ((sin(1.4902 * x₀) - (x₅ * x₅)) - 2.9947) + 0.25353
───────────────────────────────────────────────────────────────────────────────────────────────────
  - outputs\20250510_133027_1Dah7x\hall_of_fame.csv
Best by score: -x5*x5 - 2.7146482
Index 2, score=3.321948
Equation: -2.7146482 - (x5 * x5)

Index 6, score=0.058159
Equation: ((sin(1.490223 * x0) - (x5 * x5)) - 2.9946597) + 0.2535261

Index 1, score=0.016550
Equation: x2 + -76.48407

In [ ]:
model_3f_noisy_std_dev_5.fit(X, y_noisy2)
best_equation_3_noisy = model_3f_noisy_std_dev_5.sympy()
print("Best by score:", best_equation_3_noisy)


top3_3_noisy = model_3f_noisy_std_dev_5.equations_.nlargest(3, "score")

for idx, row in top3_3_noisy.iterrows():
    print(f"Index {idx}, score={row.score:.6f}")
    print("Equation:", row.equation)
    print()

c:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysr\sr.py:2776: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.548e+03  1.594e+01  y = -76.133
3           4.394e+03  1.726e-02  y = x₂ + -76.589
5           2.585e+01  2.568e+00  y = -2.8206 - (x₅ * x₅)
7           2.578e+01  1.385e-03  y = (x₅ * (-0.03127 - x₅)) + -2.8077
9           2.499e+01  1.541e-02  y = (x₀ * 0.10117) + (-2.7326 - (x₅ * x₅))
10          2.474e+01  1.011e-02  y = sin(x₄ * x₅) + (-2.8036 - (x₅ * x₅))
12          2.467e+01  1.476e-03  y = ((sin(x₄ * x₅) - (x₅ * x₅)) * 1.004) - 2.5082
14          2.449e+01  3.564e-03  y = (sin(x₄ * x₅) + ((x₁ * 0.054889) + -2.7712)) - (x₅ * x...
                                      ₅)
15          2.387e+01  2.574e-02  y = (sin(x₁ * 3.2167) + (sin(x₅ * x₄) + -2.7305)) - (x₅ * ...
                                      x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

Best by score: -x5*x5 - 2.820567
Index 2, score=2.567903
Equation: -2.820567 - (x5 * x5)

Index 8, score=0.025742
Equation: (sin(x1 * 3.216724) + (sin(x5 * x4) + -2.730506)) - (x5 * x5)

Index 1, score=0.017257
Equation: x2 + -76.58948

  - outputs\20250510_133029_NeDaRF\hall_of_fame.csv

# 5.12 Output into a DF [5.0]

In [ ]:
import pandas as pd

data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5',
    'model_1f', 'model_2f', 'model_3f',
    'model_1f_noisy', 'model_2f_noisy', 'model_3f_noisy',
    'model_1f_wide_range', 'model_2f_wide_range', 'model_3f_wide_range',
    'model_1f_noisy_std_dev_2', 'model_2f_noisy_std_dev_2', 'model_3f_noisy_std_dev_2',
    'model_1f_noisy_std_dev_5', 'model_2f_noisy_std_dev_5', 'model_3f_noisy_std_dev_5',    
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

    # Add data for the top 3 equations
    for idx, row in top3.iterrows():
        data.append([model_name, idx, row['equation'], row['score']])

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

display(df)

,Model,Equation_Type,Equation,Score
0,model_1,best,x5*x5*(-0.98154604) - 3.163106,2.031154
1,model_1,3,(x5 * x5) * -1.1931325,2.031154
2,model_1,4,(x5 * (x5 * -0.98154604)) + -3.163106,0.560019
3,model_1,2,cos(x5) + -10.987488,0.073704
4,model_2,best,-(x5*x5 - (-1)*(-0.7950349)*0.061814636) - cos...,3.442063
5,model_2,15,((-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -...,3.442063
6,model_2,3,-3.0128691 - (x5 * x5),3.142667
7,model_2,8,(-3.0203273 - cos(x0 - ((x1 - -0.7950349) * -2...,1.165197
8,model_3,best,-x5*x5 - 3.0128005,3.201109
9,model_3,3,-3.0128005 - (x5 * x5),3.201109
10,model_3,10,-2.984116 - (((sin(x1) * sin(x1)) * sin(x0)) +...,0.206831
11,model_3,2,-11.157449 - sin(x0),0.013642
12,model_1_noisy,best,x5*x5*(-0.97982454) - 3.1116526,2.018258
13,model_1_noisy,3,x5 * (x5 * -1.1879799),2.018258
14,model_1_noisy,4,((x5 * x5) * -0.97982454) + -3.1116526,0.514755
15,model_1_noisy,2,cos(x5) + -10.921997,0.074934
16,model_2_noisy,best,-x5*x5 - 2.9473116,3.038596
17,model_2_noisy,3,-2.9473116 - (x5 * x5),3.038596
18,model_2_noisy,2,cos(x5) + -10.922013,0.069191
19,model_2_noisy,12,(((sin(((x5 + -2.5165377) * (exp(x4) + -0.5469...,0.017876
20,model_3_noisy,best,-x5*x5 - 2.9473026,3.096697
21,model_3_noisy,3,-2.9473026 - (x5 * x5),3.096697
22,model_3_noisy,2,-11.091977 - sin(x0),0.011090
23,model_3_noisy,6,(((x5 + (x4 * -0.03746015)) * x5) * -0.9783922...,0.010619
24,model_1_wide_range,best,x5*x5*(-0.9992922) - 3.028511,3.273026
25,model_1_wide_range,2,x5 * (x5 * -1.0218029),3.273026
26,model_1_wide_range,3,(x5 * (x5 * -0.9992922)) + -3.028511,0.554636
27,model_1_wide_range,6,((x5 + (cos(exp(x4)) * -0.043224953)) * (x5 * ...,0.019247
28,model_2_wide_range,best,-x5*x5 - 2.9765701,3.827115
29,model_2_wide_range,2,-2.9765701 - (x5 * x5),3.827115
30,model_2_wide_range,9,((x5 * (0.013510874 - x5)) - (sin(x2 + x3) * 0...,0.034384
31,model_2_wide_range,1,x2 + -76.74522,0.016651
32,model_3_wide_range,best,-(x5*x5 - sin(x0 + x1 + x1)) - 3.0351326,3.827115
33,model_3_wide_range,2,-2.9769638 - (x5 * x5),3.827115
34,model_3_wide_range,6,-3.0351326 - ((x5 * x5) - sin(x0 + (x1 + x1))),1.183330
35,model_3_wide_range,1,x2 + -76.745186,0.016651
36,model_1_noisy_std_dev_2,best,x5*(-0.9985297)*x5 - 2.822441,3.074411
37,model_1_noisy_std_dev_2,2,x5 * (x5 * -1.0195066),3.074411
38,model_1_noisy_std_dev_2,3,((x5 * -0.9985297) * x5) + -2.822441,0.248400
39,model_1_noisy_std_dev_2,6,(((x5 * x5) + sin(x0 * -1.4498099)) * -0.99839...,0.073594
40,model_2_noisy_std_dev_2,best,-x5*x5 - 2.7146323,3.321948
41,model_2_noisy_std_dev_2,2,-2.7146323 - (x5 * x5),3.321948
42,model_2_noisy_std_dev_2,9,-2.7452788 - (cos((x0 + ((x1 * 1.9136584) + 1....,0.055915
43,model_2_noisy_std_dev_2,7,-2.863597 - ((sin(x0 * -1.4498118) + (x5 * x5)...,0.036967
44,model_3_noisy_std_dev_2,best,-x5*x5 - 2.7146482,3.321948
45,model_3_noisy_std_dev_2,2,-2.7146482 - (x5 * x5),3.321948
46,model_3_noisy_std_dev_2,6,((sin(1.490223 * x0) - (x5 * x5)) - 2.9946597)...,0.058159
47,model_3_noisy_std_dev_2,1,x2 + -76.48407,0.016550
48,model_1_noisy_std_dev_5,best,x5*(-1.0226468)*x5,2.514830
49,model_1_noisy_std_dev_5,2,(x5 * -1.0226468) * x5,2.514830
50,model_1_noisy_std_dev_5,3,((x5 * -1.0037091) * x5) + -2.5486984,0.054270
51,model_1_noisy_std_dev_5,10,(x0 * 0.0964179) + ((x5 * (x5 * -1.002817)) + ...,0.020387
52,model_2_noisy_std_dev_5,best,-x5*x5 - 2.820567,2.567903
53,model_2_noisy_std_dev_5,2,-2.820567 - (x5 * x5),2.567903
54,model_2_noisy_std_dev_5,13,sin(x4 * x5) + ((-2.5677297 - (x5 * x5)) - (si...,0.027386
55,model_2_noisy_std_dev_5,1,x2 + -76.5897,0.017257
56,model_3_noisy_std_dev_5,best,-x5*x5 - 2.820567,2.567903
57,model_3_noisy_std_dev_5,2,-2.820567 - (x5 * x5),2.567903
58,model_3_noisy_std_dev_5,8,(sin(x1 * 3.216724) + (sin(x5 * x4) + -2.73050...,0.025742
59,model_3_noisy_std_dev_5,1,x2 + -76.58948,0.017257

In [ ]:
df.to_csv('results5.csv')

In [ ]:
data = []
models = [
    'model_1', 'model_2', 'model_3',
    'model_1_noisy', 'model_2_noisy', 'model_3_noisy',
    'model_1_wide_range', 'model_2_wide_range', 'model_3_wide_range',
    'model_1_noisy_std_dev_2', 'model_2_noisy_std_dev_2', 'model_3_noisy_std_dev_2',
    'model_1_noisy_std_dev_5', 'model_2_noisy_std_dev_5', 'model_3_noisy_std_dev_5',
    'model_1f', 'model_2f', 'model_3f',
    'model_1f_noisy', 'model_2f_noisy', 'model_3f_noisy',
    'model_1f_wide_range', 'model_2f_wide_range', 'model_3f_wide_range',
    'model_1f_noisy_std_dev_2', 'model_2f_noisy_std_dev_2', 'model_3f_noisy_std_dev_2',
    'model_1f_noisy_std_dev_5', 'model_2f_noisy_std_dev_5', 'model_3f_noisy_std_dev_5',    
]

for model_name in models:
    model = globals()[model_name]  # Get the model object from the global namespace

    best_equation = model.sympy()
    top3 = model.equations_.nlargest(3, "score")

    # Add data for the best equation
    data.append([model_name, 'best', best_equation, top3.iloc[0]['score']])  # Changed to iloc to access row

df = pd.DataFrame(data, columns=['Model', 'Equation_Type', 'Equation', 'Score'])

In [ ]:
df.to_csv('results5_only_best.csv')